//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_OperationDashboard.ServiceReference2 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.WebService_ModuleUsageSoap")]
    public interface WebService_ModuleUsageSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Dept_Select", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Dept_Select();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Dept_Select", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Dept_SelectAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Module_InsertUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Module_InsertUpdate(int dept_Id, string module, string path, string createdby);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Module_InsertUpdate", ReplyAction="*")]
        System.Threading.Tasks.Task<int> Module_InsertUpdateAsync(int dept_Id, string module, string path, string createdby);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/delete_Module", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int delete_Module(string module);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/delete_Module", ReplyAction="*")]
        System.Threading.Tasks.Task<int> delete_ModuleAsync(string module);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Modules_Select", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Modules_Select();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Modules_Select", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Modules_SelectAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insert_Module_Log", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int insert_Module_Log(string module, string loguser, string logdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insert_Module_Log", ReplyAction="*")]
        System.Threading.Tasks.Task<int> insert_Module_LogAsync(string module, string loguser, string logdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Usage_Select", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Usage_Select(string fromdt, string todt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Usage_Select", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Usage_SelectAsync(string fromdt, string todt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Usage_Select_dtl", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Usage_Select_dtl(string fromdt, string todt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Usage_Select_dtl", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Usage_Select_dtlAsync(string fromdt, string todt);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService_ModuleUsageSoapChannel : Web_OperationDashboard.ServiceReference2.WebService_ModuleUsageSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService_ModuleUsageSoapClient : System.ServiceModel.ClientBase<Web_OperationDashboard.ServiceReference2.WebService_ModuleUsageSoap>, Web_OperationDashboard.ServiceReference2.WebService_ModuleUsageSoap {
        
        public WebService_ModuleUsageSoapClient() {
        }
        
        public WebService_ModuleUsageSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService_ModuleUsageSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_ModuleUsageSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_ModuleUsageSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public System.Data.DataSet Dept_Select() {
            return base.Channel.Dept_Select();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Dept_SelectAsync() {
            return base.Channel.Dept_SelectAsync();
        }
        
        public int Module_InsertUpdate(int dept_Id, string module, string path, string createdby) {
            return base.Channel.Module_InsertUpdate(dept_Id, module, path, createdby);
        }
        
        public System.Threading.Tasks.Task<int> Module_InsertUpdateAsync(int dept_Id, string module, string path, string createdby) {
            return base.Channel.Module_InsertUpdateAsync(dept_Id, module, path, createdby);
        }
        
        public int delete_Module(string module) {
            return base.Channel.delete_Module(module);
        }
        
        public System.Threading.Tasks.Task<int> delete_ModuleAsync(string module) {
            return base.Channel.delete_ModuleAsync(module);
        }
        
        public System.Data.DataSet Modules_Select() {
            return base.Channel.Modules_Select();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Modules_SelectAsync() {
            return base.Channel.Modules_SelectAsync();
        }
        
        public int insert_Module_Log(string module, string loguser, string logdate) {
            return base.Channel.insert_Module_Log(module, loguser, logdate);
        }
        
        public System.Threading.Tasks.Task<int> insert_Module_LogAsync(string module, string loguser, string logdate) {
            return base.Channel.insert_Module_LogAsync(module, loguser, logdate);
        }
        
        public System.Data.DataSet Usage_Select(string fromdt, string todt) {
            return base.Channel.Usage_Select(fromdt, todt);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Usage_SelectAsync(string fromdt, string todt) {
            return base.Channel.Usage_SelectAsync(fromdt, todt);
        }
        
        public System.Data.DataSet Usage_Select_dtl(string fromdt, string todt) {
            return base.Channel.Usage_Select_dtl(fromdt, todt);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Usage_Select_dtlAsync(string fromdt, string todt) {
            return base.Channel.Usage_Select_dtlAsync(fromdt, todt);
        }
    }
}
