//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountsApp.ServiceReference2 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.WebService_OperationSoap")]
    public interface WebService_OperationSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateUsage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int updateUsage(string path, string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateUsage", ReplyAction="*")]
        System.Threading.Tasks.Task<int> updateUsageAsync(string path, string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Login(string u_name, string pswd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> LoginAsync(string u_name, string pswd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Micro_Incharge_Select", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Micro_Incharge_Select();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Micro_Incharge_Select", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Micro_Incharge_SelectAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_Branch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Select_Branch();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_Branch", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Select_BranchAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_Microlab", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Select_Microlab();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_Microlab", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Select_MicrolabAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_Ambience", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Select_Ambience(int amb_Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_Ambience", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Select_AmbienceAsync(int amb_Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ambience_InsertUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Ambience_InsertUpdate(int amb_Id, string amb_name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ambience_InsertUpdate", ReplyAction="*")]
        System.Threading.Tasks.Task<int> Ambience_InsertUpdateAsync(int amb_Id, string amb_name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_AmbienceCondition", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Select_AmbienceCondition(int BranchId, int Month_, int Year_);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_AmbienceCondition", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Select_AmbienceConditionAsync(int BranchId, int Month_, int Year_);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_AmbienceCondition_WithId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Select_AmbienceCondition_WithId(int AMB_CONDTNID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_AmbienceCondition_WithId", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Select_AmbienceCondition_WithIdAsync(int AMB_CONDTNID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AmbienceCondtn_InsertUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int AmbienceCondtn_InsertUpdate(int branch_id, int amb_id, string count, string condtn, string remarks, int Month_, int year_, string Amb_Date, string Amb_Entered);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AmbienceCondtn_InsertUpdate", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AmbienceCondtn_InsertUpdateAsync(int branch_id, int amb_id, string count, string condtn, string remarks, int Month_, int year_, string Amb_Date, string Amb_Entered);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AmbienceCondtn_StatusUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int AmbienceCondtn_StatusUpdate(int amb_CondtnId, string reason, int checked_);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AmbienceCondtn_StatusUpdate", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AmbienceCondtn_StatusUpdateAsync(int amb_CondtnId, string reason, int checked_);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_AmbienceReport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Select_AmbienceReport(int month_, int year_, int branchId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_AmbienceReport", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Select_AmbienceReportAsync(int month_, int year_, int branchId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AmbienceCondtn_Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int AmbienceCondtn_Delete(int Month_, int Year_, int Branch_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AmbienceCondtn_Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AmbienceCondtn_DeleteAsync(int Month_, int Year_, int Branch_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AmbienceCondtn_VerifyStatusUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int AmbienceCondtn_VerifyStatusUpdate(int Month_, int Year_, int Branch_Id, string Verifn_Entered);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AmbienceCondtn_VerifyStatusUpdate", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AmbienceCondtn_VerifyStatusUpdateAsync(int Month_, int Year_, int Branch_Id, string Verifn_Entered);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_AmbienceConditionWithExcessAmbID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Select_AmbienceConditionWithExcessAmbID(int BranchId, int Month_, int Year_);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_AmbienceConditionWithExcessAmbID", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Select_AmbienceConditionWithExcessAmbIDAsync(int BranchId, int Month_, int Year_);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_Year", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Select_Year();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_Year", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Select_YearAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_VerifiedAmbience", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Select_VerifiedAmbience(int BranchId, int Month_, int Year_);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_VerifiedAmbience", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Select_VerifiedAmbienceAsync(int BranchId, int Month_, int Year_);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Change_Pswd", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Change_Pswd(string uname, string pswd, string newpswd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Change_Pswd", ReplyAction="*")]
        System.Threading.Tasks.Task<int> Change_PswdAsync(string uname, string pswd, string newpswd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AmbiencePic_InsertUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet AmbiencePic_InsertUpdate(int amb_PicId, string amb_pic_path, string amb_pic_name, int year_, int month_, int branch_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AmbiencePic_InsertUpdate", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> AmbiencePic_InsertUpdateAsync(int amb_PicId, string amb_pic_path, string amb_pic_name, int year_, int month_, int branch_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AmbiencePic_Select", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet AmbiencePic_Select(int year_, int month_, int branch_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AmbiencePic_Select", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> AmbiencePic_SelectAsync(int year_, int month_, int branch_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AmbiencePic_VerifyStatusUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int AmbiencePic_VerifyStatusUpdate(int Month_, int Year_, int Branch_Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AmbiencePic_VerifyStatusUpdate", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AmbiencePic_VerifyStatusUpdateAsync(int Month_, int Year_, int Branch_Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OperationStatus_InsertUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int OperationStatus_InsertUpdate(string type, string filename, string branch_id, string dept_id, string month, string year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OperationStatus_InsertUpdate", ReplyAction="*")]
        System.Threading.Tasks.Task<int> OperationStatus_InsertUpdateAsync(string type, string filename, string branch_id, string dept_id, string month, string year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InventoryStatus_InsertUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int InventoryStatus_InsertUpdate(string File_name, int Status, string Entered_By, string Checked_By);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InventoryStatus_InsertUpdate", ReplyAction="*")]
        System.Threading.Tasks.Task<int> InventoryStatus_InsertUpdateAsync(string File_name, int Status, string Entered_By, string Checked_By);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Inventory_StatusUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Inventory_StatusUpdate(string File_name, string Checked_By);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Inventory_StatusUpdate", ReplyAction="*")]
        System.Threading.Tasks.Task<int> Inventory_StatusUpdateAsync(string File_name, string Checked_By);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_Department", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Select_Department(int branch_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_Department", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Select_DepartmentAsync(int branch_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_Inventory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Select_Inventory(int branch_id, int deptid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_Inventory", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Select_InventoryAsync(int branch_id, int deptid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_BranchVisir_RegType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Select_BranchVisir_RegType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_BranchVisir_RegType", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Select_BranchVisir_RegTypeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_BranchVisir_AsstVerfn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Select_BranchVisir_AsstVerfn();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_BranchVisir_AsstVerfn", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Select_BranchVisir_AsstVerfnAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InventoryRegister_InsertUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int InventoryRegister_InsertUpdate(int BranchID, int dept_id, string department, string Month_, int Year_, string Entered_by, string Itemname, string Stock, string Measurement, string Unitrate, string TotalAmount, string PhysicalStock, string Deviation, string month_type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InventoryRegister_InsertUpdate", ReplyAction="*")]
        System.Threading.Tasks.Task<int> InventoryRegister_InsertUpdateAsync(int BranchID, int dept_id, string department, string Month_, int Year_, string Entered_by, string Itemname, string Stock, string Measurement, string Unitrate, string TotalAmount, string PhysicalStock, string Deviation, string month_type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_InventoryStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Select_InventoryStatus(int branch_id, int dept_id, string month, int year, string month_type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_InventoryStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Select_InventoryStatusAsync(int branch_id, int dept_id, string month, int year, string month_type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BranchVisit_Asset_InsertUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int BranchVisit_Asset_InsertUpdate(int BranchID, string Month_, int Year_, string Entered_by, string AssetVerifn, string WorkingStatus, string Remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BranchVisit_Asset_InsertUpdate", ReplyAction="*")]
        System.Threading.Tasks.Task<int> BranchVisit_Asset_InsertUpdateAsync(int BranchID, string Month_, int Year_, string Entered_by, string AssetVerifn, string WorkingStatus, string Remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_Branchvisit_Asset", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Select_Branchvisit_Asset(int branch_id, string month, int year, string Entered_by);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_Branchvisit_Asset", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Select_Branchvisit_AssetAsync(int branch_id, string month, int year, string Entered_by);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BranchVisit_CashPosition_InsertUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int BranchVisit_CashPosition_InsertUpdate(int BranchID, string Month_, int Year_, string Entered_by, string physicalcash1, string systemcash1, string diff1, string physicalcash2, string systemcash2, string diff2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BranchVisit_CashPosition_InsertUpdate", ReplyAction="*")]
        System.Threading.Tasks.Task<int> BranchVisit_CashPosition_InsertUpdateAsync(int BranchID, string Month_, int Year_, string Entered_by, string physicalcash1, string systemcash1, string diff1, string physicalcash2, string systemcash2, string diff2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_Branchvisit_Cashposition", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Select_Branchvisit_Cashposition(int branch_id, string month, int year, string Entered_by);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_Branchvisit_Cashposition", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Select_Branchvisit_CashpositionAsync(int branch_id, string month, int year, string Entered_by);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BranchVisit_Registers_InsertUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int BranchVisit_Registers_InsertUpdate(int BranchID, string Month_, int Year_, string Entered_by, string updateregister, string status, string remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BranchVisit_Registers_InsertUpdate", ReplyAction="*")]
        System.Threading.Tasks.Task<int> BranchVisit_Registers_InsertUpdateAsync(int BranchID, string Month_, int Year_, string Entered_by, string updateregister, string status, string remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_Branchvisit_Registers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Select_Branchvisit_Registers(int branch_id, string month, int year, string Entered_by);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_Branchvisit_Registers", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Select_Branchvisit_RegistersAsync(int branch_id, string month, int year, string Entered_by);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChargeRpt_Asset_InsertUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ChargeRpt_Asset_InsertUpdate(int BranchID, string Entered_by, string Asset_type, string Asset_id, string item, string make, string model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChargeRpt_Asset_InsertUpdate", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ChargeRpt_Asset_InsertUpdateAsync(int BranchID, string Entered_by, string Asset_type, string Asset_id, string item, string make, string model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_ChargeRpt_Asset", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Select_ChargeRpt_Asset(int branch_id, string entered_by);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_ChargeRpt_Asset", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Select_ChargeRpt_AssetAsync(int branch_id, string entered_by);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChargeRpt_Cash_InsertUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ChargeRpt_Cash_InsertUpdate(int BranchID, string Entered_by, string Physical1, string System1, string Diff1, string Remarks1, string Physical2, string System2, string Diff2, string Remarks2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChargeRpt_Cash_InsertUpdate", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ChargeRpt_Cash_InsertUpdateAsync(int BranchID, string Entered_by, string Physical1, string System1, string Diff1, string Remarks1, string Physical2, string System2, string Diff2, string Remarks2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_ChargeRpt_Cash", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Select_ChargeRpt_Cash(int branch_id, string Entered_by);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_ChargeRpt_Cash", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Select_ChargeRpt_CashAsync(int branch_id, string Entered_by);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChargeRpt_Registers_InsertUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ChargeRpt_Registers_InsertUpdate(int BranchID, string Entered_by, string UpdateReg, string status, string remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChargeRpt_Registers_InsertUpdate", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ChargeRpt_Registers_InsertUpdateAsync(int BranchID, string Entered_by, string UpdateReg, string status, string remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_ChargeRpt_Registers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Select_ChargeRpt_Registers(int branch_id, string entered_by);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_ChargeRpt_Registers", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Select_ChargeRpt_RegistersAsync(int branch_id, string entered_by);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChargeRpt_Doctors_InsertUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ChargeRpt_Doctors_InsertUpdate(int BranchID, string Entered_by, string Name, string Department, string Specialyst, string Visitday);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChargeRpt_Doctors_InsertUpdate", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ChargeRpt_Doctors_InsertUpdateAsync(int BranchID, string Entered_by, string Name, string Department, string Specialyst, string Visitday);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_ChargeRpt_Doctors", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Select_ChargeRpt_Doctors(int branch_id, string entered_by);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_ChargeRpt_Doctors", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Select_ChargeRpt_DoctorsAsync(int branch_id, string entered_by);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChargeRpt_Key_InsertUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ChargeRpt_Key_InsertUpdate(int BranchID, string Entered_by, string KeyName, string Count, string Missing, string Remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChargeRpt_Key_InsertUpdate", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ChargeRpt_Key_InsertUpdateAsync(int BranchID, string Entered_by, string KeyName, string Count, string Missing, string Remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_ChargeRpt_Key", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Select_ChargeRpt_Key(int branch_id, string entered_by);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_ChargeRpt_Key", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Select_ChargeRpt_KeyAsync(int branch_id, string entered_by);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChargeRpt_Vertical_InsertUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ChargeRpt_Vertical_InsertUpdate(int BranchID, string Entered_by, string Service, string Machine_Status, string WorkingCondition, string Remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChargeRpt_Vertical_InsertUpdate", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ChargeRpt_Vertical_InsertUpdateAsync(int BranchID, string Entered_by, string Service, string Machine_Status, string WorkingCondition, string Remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_ChargeRpt_Vertical", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Select_ChargeRpt_Vertical(int branch_id, string entered_by);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_ChargeRpt_Vertical", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Select_ChargeRpt_VerticalAsync(int branch_id, string entered_by);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_Branchvisit_EnteredStaff", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Select_Branchvisit_EnteredStaff(int branch_id, string month, int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_Branchvisit_EnteredStaff", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Select_Branchvisit_EnteredStaffAsync(int branch_id, string month, int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_ChargeRpt_EnteredStaff", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Select_ChargeRpt_EnteredStaff(int branch_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_ChargeRpt_EnteredStaff", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Select_ChargeRpt_EnteredStaffAsync(int branch_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_AmbienceRpt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Select_AmbienceRpt(int branch_id, int month, int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_AmbienceRpt", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Select_AmbienceRptAsync(int branch_id, int month, int year);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService_OperationSoapChannel : AccountsApp.ServiceReference2.WebService_OperationSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService_OperationSoapClient : System.ServiceModel.ClientBase<AccountsApp.ServiceReference2.WebService_OperationSoap>, AccountsApp.ServiceReference2.WebService_OperationSoap {
        
        public WebService_OperationSoapClient() {
        }
        
        public WebService_OperationSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService_OperationSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_OperationSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_OperationSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public int updateUsage(string path, string userid) {
            return base.Channel.updateUsage(path, userid);
        }
        
        public System.Threading.Tasks.Task<int> updateUsageAsync(string path, string userid) {
            return base.Channel.updateUsageAsync(path, userid);
        }
        
        public System.Data.DataSet Login(string u_name, string pswd) {
            return base.Channel.Login(u_name, pswd);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> LoginAsync(string u_name, string pswd) {
            return base.Channel.LoginAsync(u_name, pswd);
        }
        
        public System.Data.DataSet Micro_Incharge_Select() {
            return base.Channel.Micro_Incharge_Select();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Micro_Incharge_SelectAsync() {
            return base.Channel.Micro_Incharge_SelectAsync();
        }
        
        public System.Data.DataSet Select_Branch() {
            return base.Channel.Select_Branch();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Select_BranchAsync() {
            return base.Channel.Select_BranchAsync();
        }
        
        public System.Data.DataSet Select_Microlab() {
            return base.Channel.Select_Microlab();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Select_MicrolabAsync() {
            return base.Channel.Select_MicrolabAsync();
        }
        
        public System.Data.DataSet Select_Ambience(int amb_Id) {
            return base.Channel.Select_Ambience(amb_Id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Select_AmbienceAsync(int amb_Id) {
            return base.Channel.Select_AmbienceAsync(amb_Id);
        }
        
        public int Ambience_InsertUpdate(int amb_Id, string amb_name) {
            return base.Channel.Ambience_InsertUpdate(amb_Id, amb_name);
        }
        
        public System.Threading.Tasks.Task<int> Ambience_InsertUpdateAsync(int amb_Id, string amb_name) {
            return base.Channel.Ambience_InsertUpdateAsync(amb_Id, amb_name);
        }
        
        public System.Data.DataSet Select_AmbienceCondition(int BranchId, int Month_, int Year_) {
            return base.Channel.Select_AmbienceCondition(BranchId, Month_, Year_);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Select_AmbienceConditionAsync(int BranchId, int Month_, int Year_) {
            return base.Channel.Select_AmbienceConditionAsync(BranchId, Month_, Year_);
        }
        
        public System.Data.DataSet Select_AmbienceCondition_WithId(int AMB_CONDTNID) {
            return base.Channel.Select_AmbienceCondition_WithId(AMB_CONDTNID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Select_AmbienceCondition_WithIdAsync(int AMB_CONDTNID) {
            return base.Channel.Select_AmbienceCondition_WithIdAsync(AMB_CONDTNID);
        }
        
        public int AmbienceCondtn_InsertUpdate(int branch_id, int amb_id, string count, string condtn, string remarks, int Month_, int year_, string Amb_Date, string Amb_Entered) {
            return base.Channel.AmbienceCondtn_InsertUpdate(branch_id, amb_id, count, condtn, remarks, Month_, year_, Amb_Date, Amb_Entered);
        }
        
        public System.Threading.Tasks.Task<int> AmbienceCondtn_InsertUpdateAsync(int branch_id, int amb_id, string count, string condtn, string remarks, int Month_, int year_, string Amb_Date, string Amb_Entered) {
            return base.Channel.AmbienceCondtn_InsertUpdateAsync(branch_id, amb_id, count, condtn, remarks, Month_, year_, Amb_Date, Amb_Entered);
        }
        
        public int AmbienceCondtn_StatusUpdate(int amb_CondtnId, string reason, int checked_) {
            return base.Channel.AmbienceCondtn_StatusUpdate(amb_CondtnId, reason, checked_);
        }
        
        public System.Threading.Tasks.Task<int> AmbienceCondtn_StatusUpdateAsync(int amb_CondtnId, string reason, int checked_) {
            return base.Channel.AmbienceCondtn_StatusUpdateAsync(amb_CondtnId, reason, checked_);
        }
        
        public System.Data.DataSet Select_AmbienceReport(int month_, int year_, int branchId) {
            return base.Channel.Select_AmbienceReport(month_, year_, branchId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Select_AmbienceReportAsync(int month_, int year_, int branchId) {
            return base.Channel.Select_AmbienceReportAsync(month_, year_, branchId);
        }
        
        public int AmbienceCondtn_Delete(int Month_, int Year_, int Branch_id) {
            return base.Channel.AmbienceCondtn_Delete(Month_, Year_, Branch_id);
        }
        
        public System.Threading.Tasks.Task<int> AmbienceCondtn_DeleteAsync(int Month_, int Year_, int Branch_id) {
            return base.Channel.AmbienceCondtn_DeleteAsync(Month_, Year_, Branch_id);
        }
        
        public int AmbienceCondtn_VerifyStatusUpdate(int Month_, int Year_, int Branch_Id, string Verifn_Entered) {
            return base.Channel.AmbienceCondtn_VerifyStatusUpdate(Month_, Year_, Branch_Id, Verifn_Entered);
        }
        
        public System.Threading.Tasks.Task<int> AmbienceCondtn_VerifyStatusUpdateAsync(int Month_, int Year_, int Branch_Id, string Verifn_Entered) {
            return base.Channel.AmbienceCondtn_VerifyStatusUpdateAsync(Month_, Year_, Branch_Id, Verifn_Entered);
        }
        
        public System.Data.DataSet Select_AmbienceConditionWithExcessAmbID(int BranchId, int Month_, int Year_) {
            return base.Channel.Select_AmbienceConditionWithExcessAmbID(BranchId, Month_, Year_);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Select_AmbienceConditionWithExcessAmbIDAsync(int BranchId, int Month_, int Year_) {
            return base.Channel.Select_AmbienceConditionWithExcessAmbIDAsync(BranchId, Month_, Year_);
        }
        
        public System.Data.DataSet Select_Year() {
            return base.Channel.Select_Year();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Select_YearAsync() {
            return base.Channel.Select_YearAsync();
        }
        
        public System.Data.DataSet Select_VerifiedAmbience(int BranchId, int Month_, int Year_) {
            return base.Channel.Select_VerifiedAmbience(BranchId, Month_, Year_);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Select_VerifiedAmbienceAsync(int BranchId, int Month_, int Year_) {
            return base.Channel.Select_VerifiedAmbienceAsync(BranchId, Month_, Year_);
        }
        
        public int Change_Pswd(string uname, string pswd, string newpswd) {
            return base.Channel.Change_Pswd(uname, pswd, newpswd);
        }
        
        public System.Threading.Tasks.Task<int> Change_PswdAsync(string uname, string pswd, string newpswd) {
            return base.Channel.Change_PswdAsync(uname, pswd, newpswd);
        }
        
        public System.Data.DataSet AmbiencePic_InsertUpdate(int amb_PicId, string amb_pic_path, string amb_pic_name, int year_, int month_, int branch_id) {
            return base.Channel.AmbiencePic_InsertUpdate(amb_PicId, amb_pic_path, amb_pic_name, year_, month_, branch_id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> AmbiencePic_InsertUpdateAsync(int amb_PicId, string amb_pic_path, string amb_pic_name, int year_, int month_, int branch_id) {
            return base.Channel.AmbiencePic_InsertUpdateAsync(amb_PicId, amb_pic_path, amb_pic_name, year_, month_, branch_id);
        }
        
        public System.Data.DataSet AmbiencePic_Select(int year_, int month_, int branch_id) {
            return base.Channel.AmbiencePic_Select(year_, month_, branch_id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> AmbiencePic_SelectAsync(int year_, int month_, int branch_id) {
            return base.Channel.AmbiencePic_SelectAsync(year_, month_, branch_id);
        }
        
        public int AmbiencePic_VerifyStatusUpdate(int Month_, int Year_, int Branch_Id) {
            return base.Channel.AmbiencePic_VerifyStatusUpdate(Month_, Year_, Branch_Id);
        }
        
        public System.Threading.Tasks.Task<int> AmbiencePic_VerifyStatusUpdateAsync(int Month_, int Year_, int Branch_Id) {
            return base.Channel.AmbiencePic_VerifyStatusUpdateAsync(Month_, Year_, Branch_Id);
        }
        
        public int OperationStatus_InsertUpdate(string type, string filename, string branch_id, string dept_id, string month, string year) {
            return base.Channel.OperationStatus_InsertUpdate(type, filename, branch_id, dept_id, month, year);
        }
        
        public System.Threading.Tasks.Task<int> OperationStatus_InsertUpdateAsync(string type, string filename, string branch_id, string dept_id, string month, string year) {
            return base.Channel.OperationStatus_InsertUpdateAsync(type, filename, branch_id, dept_id, month, year);
        }
        
        public int InventoryStatus_InsertUpdate(string File_name, int Status, string Entered_By, string Checked_By) {
            return base.Channel.InventoryStatus_InsertUpdate(File_name, Status, Entered_By, Checked_By);
        }
        
        public System.Threading.Tasks.Task<int> InventoryStatus_InsertUpdateAsync(string File_name, int Status, string Entered_By, string Checked_By) {
            return base.Channel.InventoryStatus_InsertUpdateAsync(File_name, Status, Entered_By, Checked_By);
        }
        
        public int Inventory_StatusUpdate(string File_name, string Checked_By) {
            return base.Channel.Inventory_StatusUpdate(File_name, Checked_By);
        }
        
        public System.Threading.Tasks.Task<int> Inventory_StatusUpdateAsync(string File_name, string Checked_By) {
            return base.Channel.Inventory_StatusUpdateAsync(File_name, Checked_By);
        }
        
        public System.Data.DataSet Select_Department(int branch_id) {
            return base.Channel.Select_Department(branch_id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Select_DepartmentAsync(int branch_id) {
            return base.Channel.Select_DepartmentAsync(branch_id);
        }
        
        public System.Data.DataSet Select_Inventory(int branch_id, int deptid) {
            return base.Channel.Select_Inventory(branch_id, deptid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Select_InventoryAsync(int branch_id, int deptid) {
            return base.Channel.Select_InventoryAsync(branch_id, deptid);
        }
        
        public System.Data.DataSet Select_BranchVisir_RegType() {
            return base.Channel.Select_BranchVisir_RegType();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Select_BranchVisir_RegTypeAsync() {
            return base.Channel.Select_BranchVisir_RegTypeAsync();
        }
        
        public System.Data.DataSet Select_BranchVisir_AsstVerfn() {
            return base.Channel.Select_BranchVisir_AsstVerfn();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Select_BranchVisir_AsstVerfnAsync() {
            return base.Channel.Select_BranchVisir_AsstVerfnAsync();
        }
        
        public int InventoryRegister_InsertUpdate(int BranchID, int dept_id, string department, string Month_, int Year_, string Entered_by, string Itemname, string Stock, string Measurement, string Unitrate, string TotalAmount, string PhysicalStock, string Deviation, string month_type) {
            return base.Channel.InventoryRegister_InsertUpdate(BranchID, dept_id, department, Month_, Year_, Entered_by, Itemname, Stock, Measurement, Unitrate, TotalAmount, PhysicalStock, Deviation, month_type);
        }
        
        public System.Threading.Tasks.Task<int> InventoryRegister_InsertUpdateAsync(int BranchID, int dept_id, string department, string Month_, int Year_, string Entered_by, string Itemname, string Stock, string Measurement, string Unitrate, string TotalAmount, string PhysicalStock, string Deviation, string month_type) {
            return base.Channel.InventoryRegister_InsertUpdateAsync(BranchID, dept_id, department, Month_, Year_, Entered_by, Itemname, Stock, Measurement, Unitrate, TotalAmount, PhysicalStock, Deviation, month_type);
        }
        
        public System.Data.DataSet Select_InventoryStatus(int branch_id, int dept_id, string month, int year, string month_type) {
            return base.Channel.Select_InventoryStatus(branch_id, dept_id, month, year, month_type);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Select_InventoryStatusAsync(int branch_id, int dept_id, string month, int year, string month_type) {
            return base.Channel.Select_InventoryStatusAsync(branch_id, dept_id, month, year, month_type);
        }
        
        public int BranchVisit_Asset_InsertUpdate(int BranchID, string Month_, int Year_, string Entered_by, string AssetVerifn, string WorkingStatus, string Remarks) {
            return base.Channel.BranchVisit_Asset_InsertUpdate(BranchID, Month_, Year_, Entered_by, AssetVerifn, WorkingStatus, Remarks);
        }
        
        public System.Threading.Tasks.Task<int> BranchVisit_Asset_InsertUpdateAsync(int BranchID, string Month_, int Year_, string Entered_by, string AssetVerifn, string WorkingStatus, string Remarks) {
            return base.Channel.BranchVisit_Asset_InsertUpdateAsync(BranchID, Month_, Year_, Entered_by, AssetVerifn, WorkingStatus, Remarks);
        }
        
        public System.Data.DataSet Select_Branchvisit_Asset(int branch_id, string month, int year, string Entered_by) {
            return base.Channel.Select_Branchvisit_Asset(branch_id, month, year, Entered_by);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Select_Branchvisit_AssetAsync(int branch_id, string month, int year, string Entered_by) {
            return base.Channel.Select_Branchvisit_AssetAsync(branch_id, month, year, Entered_by);
        }
        
        public int BranchVisit_CashPosition_InsertUpdate(int BranchID, string Month_, int Year_, string Entered_by, string physicalcash1, string systemcash1, string diff1, string physicalcash2, string systemcash2, string diff2) {
            return base.Channel.BranchVisit_CashPosition_InsertUpdate(BranchID, Month_, Year_, Entered_by, physicalcash1, systemcash1, diff1, physicalcash2, systemcash2, diff2);
        }
        
        public System.Threading.Tasks.Task<int> BranchVisit_CashPosition_InsertUpdateAsync(int BranchID, string Month_, int Year_, string Entered_by, string physicalcash1, string systemcash1, string diff1, string physicalcash2, string systemcash2, string diff2) {
            return base.Channel.BranchVisit_CashPosition_InsertUpdateAsync(BranchID, Month_, Year_, Entered_by, physicalcash1, systemcash1, diff1, physicalcash2, systemcash2, diff2);
        }
        
        public System.Data.DataSet Select_Branchvisit_Cashposition(int branch_id, string month, int year, string Entered_by) {
            return base.Channel.Select_Branchvisit_Cashposition(branch_id, month, year, Entered_by);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Select_Branchvisit_CashpositionAsync(int branch_id, string month, int year, string Entered_by) {
            return base.Channel.Select_Branchvisit_CashpositionAsync(branch_id, month, year, Entered_by);
        }
        
        public int BranchVisit_Registers_InsertUpdate(int BranchID, string Month_, int Year_, string Entered_by, string updateregister, string status, string remarks) {
            return base.Channel.BranchVisit_Registers_InsertUpdate(BranchID, Month_, Year_, Entered_by, updateregister, status, remarks);
        }
        
        public System.Threading.Tasks.Task<int> BranchVisit_Registers_InsertUpdateAsync(int BranchID, string Month_, int Year_, string Entered_by, string updateregister, string status, string remarks) {
            return base.Channel.BranchVisit_Registers_InsertUpdateAsync(BranchID, Month_, Year_, Entered_by, updateregister, status, remarks);
        }
        
        public System.Data.DataSet Select_Branchvisit_Registers(int branch_id, string month, int year, string Entered_by) {
            return base.Channel.Select_Branchvisit_Registers(branch_id, month, year, Entered_by);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Select_Branchvisit_RegistersAsync(int branch_id, string month, int year, string Entered_by) {
            return base.Channel.Select_Branchvisit_RegistersAsync(branch_id, month, year, Entered_by);
        }
        
        public int ChargeRpt_Asset_InsertUpdate(int BranchID, string Entered_by, string Asset_type, string Asset_id, string item, string make, string model) {
            return base.Channel.ChargeRpt_Asset_InsertUpdate(BranchID, Entered_by, Asset_type, Asset_id, item, make, model);
        }
        
        public System.Threading.Tasks.Task<int> ChargeRpt_Asset_InsertUpdateAsync(int BranchID, string Entered_by, string Asset_type, string Asset_id, string item, string make, string model) {
            return base.Channel.ChargeRpt_Asset_InsertUpdateAsync(BranchID, Entered_by, Asset_type, Asset_id, item, make, model);
        }
        
        public System.Data.DataSet Select_ChargeRpt_Asset(int branch_id, string entered_by) {
            return base.Channel.Select_ChargeRpt_Asset(branch_id, entered_by);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Select_ChargeRpt_AssetAsync(int branch_id, string entered_by) {
            return base.Channel.Select_ChargeRpt_AssetAsync(branch_id, entered_by);
        }
        
        public int ChargeRpt_Cash_InsertUpdate(int BranchID, string Entered_by, string Physical1, string System1, string Diff1, string Remarks1, string Physical2, string System2, string Diff2, string Remarks2) {
            return base.Channel.ChargeRpt_Cash_InsertUpdate(BranchID, Entered_by, Physical1, System1, Diff1, Remarks1, Physical2, System2, Diff2, Remarks2);
        }
        
        public System.Threading.Tasks.Task<int> ChargeRpt_Cash_InsertUpdateAsync(int BranchID, string Entered_by, string Physical1, string System1, string Diff1, string Remarks1, string Physical2, string System2, string Diff2, string Remarks2) {
            return base.Channel.ChargeRpt_Cash_InsertUpdateAsync(BranchID, Entered_by, Physical1, System1, Diff1, Remarks1, Physical2, System2, Diff2, Remarks2);
        }
        
        public System.Data.DataSet Select_ChargeRpt_Cash(int branch_id, string Entered_by) {
            return base.Channel.Select_ChargeRpt_Cash(branch_id, Entered_by);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Select_ChargeRpt_CashAsync(int branch_id, string Entered_by) {
            return base.Channel.Select_ChargeRpt_CashAsync(branch_id, Entered_by);
        }
        
        public int ChargeRpt_Registers_InsertUpdate(int BranchID, string Entered_by, string UpdateReg, string status, string remarks) {
            return base.Channel.ChargeRpt_Registers_InsertUpdate(BranchID, Entered_by, UpdateReg, status, remarks);
        }
        
        public System.Threading.Tasks.Task<int> ChargeRpt_Registers_InsertUpdateAsync(int BranchID, string Entered_by, string UpdateReg, string status, string remarks) {
            return base.Channel.ChargeRpt_Registers_InsertUpdateAsync(BranchID, Entered_by, UpdateReg, status, remarks);
        }
        
        public System.Data.DataSet Select_ChargeRpt_Registers(int branch_id, string entered_by) {
            return base.Channel.Select_ChargeRpt_Registers(branch_id, entered_by);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Select_ChargeRpt_RegistersAsync(int branch_id, string entered_by) {
            return base.Channel.Select_ChargeRpt_RegistersAsync(branch_id, entered_by);
        }
        
        public int ChargeRpt_Doctors_InsertUpdate(int BranchID, string Entered_by, string Name, string Department, string Specialyst, string Visitday) {
            return base.Channel.ChargeRpt_Doctors_InsertUpdate(BranchID, Entered_by, Name, Department, Specialyst, Visitday);
        }
        
        public System.Threading.Tasks.Task<int> ChargeRpt_Doctors_InsertUpdateAsync(int BranchID, string Entered_by, string Name, string Department, string Specialyst, string Visitday) {
            return base.Channel.ChargeRpt_Doctors_InsertUpdateAsync(BranchID, Entered_by, Name, Department, Specialyst, Visitday);
        }
        
        public System.Data.DataSet Select_ChargeRpt_Doctors(int branch_id, string entered_by) {
            return base.Channel.Select_ChargeRpt_Doctors(branch_id, entered_by);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Select_ChargeRpt_DoctorsAsync(int branch_id, string entered_by) {
            return base.Channel.Select_ChargeRpt_DoctorsAsync(branch_id, entered_by);
        }
        
        public int ChargeRpt_Key_InsertUpdate(int BranchID, string Entered_by, string KeyName, string Count, string Missing, string Remarks) {
            return base.Channel.ChargeRpt_Key_InsertUpdate(BranchID, Entered_by, KeyName, Count, Missing, Remarks);
        }
        
        public System.Threading.Tasks.Task<int> ChargeRpt_Key_InsertUpdateAsync(int BranchID, string Entered_by, string KeyName, string Count, string Missing, string Remarks) {
            return base.Channel.ChargeRpt_Key_InsertUpdateAsync(BranchID, Entered_by, KeyName, Count, Missing, Remarks);
        }
        
        public System.Data.DataSet Select_ChargeRpt_Key(int branch_id, string entered_by) {
            return base.Channel.Select_ChargeRpt_Key(branch_id, entered_by);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Select_ChargeRpt_KeyAsync(int branch_id, string entered_by) {
            return base.Channel.Select_ChargeRpt_KeyAsync(branch_id, entered_by);
        }
        
        public int ChargeRpt_Vertical_InsertUpdate(int BranchID, string Entered_by, string Service, string Machine_Status, string WorkingCondition, string Remarks) {
            return base.Channel.ChargeRpt_Vertical_InsertUpdate(BranchID, Entered_by, Service, Machine_Status, WorkingCondition, Remarks);
        }
        
        public System.Threading.Tasks.Task<int> ChargeRpt_Vertical_InsertUpdateAsync(int BranchID, string Entered_by, string Service, string Machine_Status, string WorkingCondition, string Remarks) {
            return base.Channel.ChargeRpt_Vertical_InsertUpdateAsync(BranchID, Entered_by, Service, Machine_Status, WorkingCondition, Remarks);
        }
        
        public System.Data.DataSet Select_ChargeRpt_Vertical(int branch_id, string entered_by) {
            return base.Channel.Select_ChargeRpt_Vertical(branch_id, entered_by);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Select_ChargeRpt_VerticalAsync(int branch_id, string entered_by) {
            return base.Channel.Select_ChargeRpt_VerticalAsync(branch_id, entered_by);
        }
        
        public System.Data.DataSet Select_Branchvisit_EnteredStaff(int branch_id, string month, int year) {
            return base.Channel.Select_Branchvisit_EnteredStaff(branch_id, month, year);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Select_Branchvisit_EnteredStaffAsync(int branch_id, string month, int year) {
            return base.Channel.Select_Branchvisit_EnteredStaffAsync(branch_id, month, year);
        }
        
        public System.Data.DataSet Select_ChargeRpt_EnteredStaff(int branch_id) {
            return base.Channel.Select_ChargeRpt_EnteredStaff(branch_id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Select_ChargeRpt_EnteredStaffAsync(int branch_id) {
            return base.Channel.Select_ChargeRpt_EnteredStaffAsync(branch_id);
        }
        
        public System.Data.DataSet Select_AmbienceRpt(int branch_id, int month, int year) {
            return base.Channel.Select_AmbienceRpt(branch_id, month, year);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Select_AmbienceRptAsync(int branch_id, int month, int year) {
            return base.Channel.Select_AmbienceRptAsync(branch_id, month, year);
        }
    }
}
