//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthcheckupAlert.ServiceReference_HealthCheckupalert {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference_HealthCheckupalert.Service_HealthCheckupReminderSoap")]
    public interface Service_HealthCheckupReminderSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTestdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetTestdate();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service_HealthCheckupReminderSoapChannel : HealthcheckupAlert.ServiceReference_HealthCheckupalert.Service_HealthCheckupReminderSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service_HealthCheckupReminderSoapClient : System.ServiceModel.ClientBase<HealthcheckupAlert.ServiceReference_HealthCheckupalert.Service_HealthCheckupReminderSoap>, HealthcheckupAlert.ServiceReference_HealthCheckupalert.Service_HealthCheckupReminderSoap {
        
        public Service_HealthCheckupReminderSoapClient() {
        }
        
        public Service_HealthCheckupReminderSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service_HealthCheckupReminderSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_HealthCheckupReminderSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_HealthCheckupReminderSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Data.DataSet GetTestdate() {
            return base.Channel.GetTestdate();
        }
    }
}
