//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOP_and_KRA.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.Service_SOPandKRASoap")]
    public interface Service_SOPandKRASoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_login", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_loginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_dapartment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_dapartment();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_dapartment", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_dapartmentAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_Sopkra", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Add_Sopkra(string sopkraid, string dep_name, string designation, string sop_doc, string kra_doc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_Sopkra", ReplyAction="*")]
        System.Threading.Tasks.Task<int> Add_SopkraAsync(string sopkraid, string dep_name, string designation, string sop_doc, string kra_doc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_sopkraid", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_sopkraid();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_sopkraid", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_sopkraidAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_viewsopkra", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_viewsopkra();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_viewsopkra", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_viewsopkraAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_registerddesignation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_registerddesignation(int dept_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_registerddesignation", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_registerddesignationAsync(int dept_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_registerdsopkra", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_registerdsopkra(string sop_kra_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_registerdsopkra", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_registerdsopkraAsync(string sop_kra_id);
        
        // CODEGEN: Parameter 'sop_attachment' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_sop", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SOP_and_KRA.ServiceReference1.Update_sopResponse Update_sop(SOP_and_KRA.ServiceReference1.Update_sopRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_sop", ReplyAction="*")]
        System.Threading.Tasks.Task<SOP_and_KRA.ServiceReference1.Update_sopResponse> Update_sopAsync(SOP_and_KRA.ServiceReference1.Update_sopRequest request);
        
        // CODEGEN: Parameter 'kra_attachment' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_kra", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SOP_and_KRA.ServiceReference1.Update_kraResponse Update_kra(SOP_and_KRA.ServiceReference1.Update_kraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_kra", ReplyAction="*")]
        System.Threading.Tasks.Task<SOP_and_KRA.ServiceReference1.Update_kraResponse> Update_kraAsync(SOP_and_KRA.ServiceReference1.Update_kraRequest request);
        
        // CODEGEN: Parameter 'sop_attachment' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_sopkra", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SOP_and_KRA.ServiceReference1.Update_sopkraResponse Update_sopkra(SOP_and_KRA.ServiceReference1.Update_sopkraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_sopkra", ReplyAction="*")]
        System.Threading.Tasks.Task<SOP_and_KRA.ServiceReference1.Update_sopkraResponse> Update_sopkraAsync(SOP_and_KRA.ServiceReference1.Update_sopkraRequest request);
        
        // CODEGEN: Parameter 'sop_attachment' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_Compliance", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SOP_and_KRA.ServiceReference1.Insert_ComplianceResponse Insert_Compliance(SOP_and_KRA.ServiceReference1.Insert_ComplianceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_Compliance", ReplyAction="*")]
        System.Threading.Tasks.Task<SOP_and_KRA.ServiceReference1.Insert_ComplianceResponse> Insert_ComplianceAsync(SOP_and_KRA.ServiceReference1.Insert_ComplianceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_sop", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Update_sopRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sop_kra_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] sop_attachment;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string sop_filename;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string sop_contenttype;
        
        public Update_sopRequest() {
        }
        
        public Update_sopRequest(string sop_kra_id, byte[] sop_attachment, string sop_filename, string sop_contenttype) {
            this.sop_kra_id = sop_kra_id;
            this.sop_attachment = sop_attachment;
            this.sop_filename = sop_filename;
            this.sop_contenttype = sop_contenttype;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_sopResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Update_sopResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int Update_sopResult;
        
        public Update_sopResponse() {
        }
        
        public Update_sopResponse(int Update_sopResult) {
            this.Update_sopResult = Update_sopResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_kra", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Update_kraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sop_kra_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] kra_attachment;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string kra_filename;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string kra_contenttype;
        
        public Update_kraRequest() {
        }
        
        public Update_kraRequest(string sop_kra_id, byte[] kra_attachment, string kra_filename, string kra_contenttype) {
            this.sop_kra_id = sop_kra_id;
            this.kra_attachment = kra_attachment;
            this.kra_filename = kra_filename;
            this.kra_contenttype = kra_contenttype;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_kraResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Update_kraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int Update_kraResult;
        
        public Update_kraResponse() {
        }
        
        public Update_kraResponse(int Update_kraResult) {
            this.Update_kraResult = Update_kraResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_sopkra", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Update_sopkraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sop_kra_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] sop_attachment;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string sop_filename;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string sop_contenttype;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] kra_attachment;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string kra_filename;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string kra_contenttype;
        
        public Update_sopkraRequest() {
        }
        
        public Update_sopkraRequest(string sop_kra_id, byte[] sop_attachment, string sop_filename, string sop_contenttype, byte[] kra_attachment, string kra_filename, string kra_contenttype) {
            this.sop_kra_id = sop_kra_id;
            this.sop_attachment = sop_attachment;
            this.sop_filename = sop_filename;
            this.sop_contenttype = sop_contenttype;
            this.kra_attachment = kra_attachment;
            this.kra_filename = kra_filename;
            this.kra_contenttype = kra_contenttype;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_sopkraResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Update_sopkraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int Update_sopkraResult;
        
        public Update_sopkraResponse() {
        }
        
        public Update_sopkraResponse(int Update_sopkraResult) {
            this.Update_sopkraResult = Update_sopkraResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Insert_Compliance", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Insert_ComplianceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string dept_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string designation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] sop_attachment;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string sop_filename;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string sop_contenttype;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] kra_attachment;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string kra_filename;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string kra_contenttype;
        
        public Insert_ComplianceRequest() {
        }
        
        public Insert_ComplianceRequest(string dept_id, string designation, byte[] sop_attachment, string sop_filename, string sop_contenttype, byte[] kra_attachment, string kra_filename, string kra_contenttype) {
            this.dept_id = dept_id;
            this.designation = designation;
            this.sop_attachment = sop_attachment;
            this.sop_filename = sop_filename;
            this.sop_contenttype = sop_contenttype;
            this.kra_attachment = kra_attachment;
            this.kra_filename = kra_filename;
            this.kra_contenttype = kra_contenttype;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Insert_ComplianceResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Insert_ComplianceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int Insert_ComplianceResult;
        
        public Insert_ComplianceResponse() {
        }
        
        public Insert_ComplianceResponse(int Insert_ComplianceResult) {
            this.Insert_ComplianceResult = Insert_ComplianceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service_SOPandKRASoapChannel : SOP_and_KRA.ServiceReference1.Service_SOPandKRASoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service_SOPandKRASoapClient : System.ServiceModel.ClientBase<SOP_and_KRA.ServiceReference1.Service_SOPandKRASoap>, SOP_and_KRA.ServiceReference1.Service_SOPandKRASoap {
        
        public Service_SOPandKRASoapClient() {
        }
        
        public Service_SOPandKRASoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service_SOPandKRASoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_SOPandKRASoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_SOPandKRASoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet Get_login(string username, string password) {
            return base.Channel.Get_login(username, password);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_loginAsync(string username, string password) {
            return base.Channel.Get_loginAsync(username, password);
        }
        
        public System.Data.DataSet Get_dapartment() {
            return base.Channel.Get_dapartment();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_dapartmentAsync() {
            return base.Channel.Get_dapartmentAsync();
        }
        
        public int Add_Sopkra(string sopkraid, string dep_name, string designation, string sop_doc, string kra_doc) {
            return base.Channel.Add_Sopkra(sopkraid, dep_name, designation, sop_doc, kra_doc);
        }
        
        public System.Threading.Tasks.Task<int> Add_SopkraAsync(string sopkraid, string dep_name, string designation, string sop_doc, string kra_doc) {
            return base.Channel.Add_SopkraAsync(sopkraid, dep_name, designation, sop_doc, kra_doc);
        }
        
        public System.Data.DataSet Get_sopkraid() {
            return base.Channel.Get_sopkraid();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_sopkraidAsync() {
            return base.Channel.Get_sopkraidAsync();
        }
        
        public System.Data.DataSet Get_viewsopkra() {
            return base.Channel.Get_viewsopkra();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_viewsopkraAsync() {
            return base.Channel.Get_viewsopkraAsync();
        }
        
        public System.Data.DataSet Get_registerddesignation(int dept_id) {
            return base.Channel.Get_registerddesignation(dept_id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_registerddesignationAsync(int dept_id) {
            return base.Channel.Get_registerddesignationAsync(dept_id);
        }
        
        public System.Data.DataSet Get_registerdsopkra(string sop_kra_id) {
            return base.Channel.Get_registerdsopkra(sop_kra_id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_registerdsopkraAsync(string sop_kra_id) {
            return base.Channel.Get_registerdsopkraAsync(sop_kra_id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOP_and_KRA.ServiceReference1.Update_sopResponse SOP_and_KRA.ServiceReference1.Service_SOPandKRASoap.Update_sop(SOP_and_KRA.ServiceReference1.Update_sopRequest request) {
            return base.Channel.Update_sop(request);
        }
        
        public int Update_sop(string sop_kra_id, byte[] sop_attachment, string sop_filename, string sop_contenttype) {
            SOP_and_KRA.ServiceReference1.Update_sopRequest inValue = new SOP_and_KRA.ServiceReference1.Update_sopRequest();
            inValue.sop_kra_id = sop_kra_id;
            inValue.sop_attachment = sop_attachment;
            inValue.sop_filename = sop_filename;
            inValue.sop_contenttype = sop_contenttype;
            SOP_and_KRA.ServiceReference1.Update_sopResponse retVal = ((SOP_and_KRA.ServiceReference1.Service_SOPandKRASoap)(this)).Update_sop(inValue);
            return retVal.Update_sopResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOP_and_KRA.ServiceReference1.Update_sopResponse> SOP_and_KRA.ServiceReference1.Service_SOPandKRASoap.Update_sopAsync(SOP_and_KRA.ServiceReference1.Update_sopRequest request) {
            return base.Channel.Update_sopAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOP_and_KRA.ServiceReference1.Update_sopResponse> Update_sopAsync(string sop_kra_id, byte[] sop_attachment, string sop_filename, string sop_contenttype) {
            SOP_and_KRA.ServiceReference1.Update_sopRequest inValue = new SOP_and_KRA.ServiceReference1.Update_sopRequest();
            inValue.sop_kra_id = sop_kra_id;
            inValue.sop_attachment = sop_attachment;
            inValue.sop_filename = sop_filename;
            inValue.sop_contenttype = sop_contenttype;
            return ((SOP_and_KRA.ServiceReference1.Service_SOPandKRASoap)(this)).Update_sopAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOP_and_KRA.ServiceReference1.Update_kraResponse SOP_and_KRA.ServiceReference1.Service_SOPandKRASoap.Update_kra(SOP_and_KRA.ServiceReference1.Update_kraRequest request) {
            return base.Channel.Update_kra(request);
        }
        
        public int Update_kra(string sop_kra_id, byte[] kra_attachment, string kra_filename, string kra_contenttype) {
            SOP_and_KRA.ServiceReference1.Update_kraRequest inValue = new SOP_and_KRA.ServiceReference1.Update_kraRequest();
            inValue.sop_kra_id = sop_kra_id;
            inValue.kra_attachment = kra_attachment;
            inValue.kra_filename = kra_filename;
            inValue.kra_contenttype = kra_contenttype;
            SOP_and_KRA.ServiceReference1.Update_kraResponse retVal = ((SOP_and_KRA.ServiceReference1.Service_SOPandKRASoap)(this)).Update_kra(inValue);
            return retVal.Update_kraResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOP_and_KRA.ServiceReference1.Update_kraResponse> SOP_and_KRA.ServiceReference1.Service_SOPandKRASoap.Update_kraAsync(SOP_and_KRA.ServiceReference1.Update_kraRequest request) {
            return base.Channel.Update_kraAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOP_and_KRA.ServiceReference1.Update_kraResponse> Update_kraAsync(string sop_kra_id, byte[] kra_attachment, string kra_filename, string kra_contenttype) {
            SOP_and_KRA.ServiceReference1.Update_kraRequest inValue = new SOP_and_KRA.ServiceReference1.Update_kraRequest();
            inValue.sop_kra_id = sop_kra_id;
            inValue.kra_attachment = kra_attachment;
            inValue.kra_filename = kra_filename;
            inValue.kra_contenttype = kra_contenttype;
            return ((SOP_and_KRA.ServiceReference1.Service_SOPandKRASoap)(this)).Update_kraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOP_and_KRA.ServiceReference1.Update_sopkraResponse SOP_and_KRA.ServiceReference1.Service_SOPandKRASoap.Update_sopkra(SOP_and_KRA.ServiceReference1.Update_sopkraRequest request) {
            return base.Channel.Update_sopkra(request);
        }
        
        public int Update_sopkra(string sop_kra_id, byte[] sop_attachment, string sop_filename, string sop_contenttype, byte[] kra_attachment, string kra_filename, string kra_contenttype) {
            SOP_and_KRA.ServiceReference1.Update_sopkraRequest inValue = new SOP_and_KRA.ServiceReference1.Update_sopkraRequest();
            inValue.sop_kra_id = sop_kra_id;
            inValue.sop_attachment = sop_attachment;
            inValue.sop_filename = sop_filename;
            inValue.sop_contenttype = sop_contenttype;
            inValue.kra_attachment = kra_attachment;
            inValue.kra_filename = kra_filename;
            inValue.kra_contenttype = kra_contenttype;
            SOP_and_KRA.ServiceReference1.Update_sopkraResponse retVal = ((SOP_and_KRA.ServiceReference1.Service_SOPandKRASoap)(this)).Update_sopkra(inValue);
            return retVal.Update_sopkraResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOP_and_KRA.ServiceReference1.Update_sopkraResponse> SOP_and_KRA.ServiceReference1.Service_SOPandKRASoap.Update_sopkraAsync(SOP_and_KRA.ServiceReference1.Update_sopkraRequest request) {
            return base.Channel.Update_sopkraAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOP_and_KRA.ServiceReference1.Update_sopkraResponse> Update_sopkraAsync(string sop_kra_id, byte[] sop_attachment, string sop_filename, string sop_contenttype, byte[] kra_attachment, string kra_filename, string kra_contenttype) {
            SOP_and_KRA.ServiceReference1.Update_sopkraRequest inValue = new SOP_and_KRA.ServiceReference1.Update_sopkraRequest();
            inValue.sop_kra_id = sop_kra_id;
            inValue.sop_attachment = sop_attachment;
            inValue.sop_filename = sop_filename;
            inValue.sop_contenttype = sop_contenttype;
            inValue.kra_attachment = kra_attachment;
            inValue.kra_filename = kra_filename;
            inValue.kra_contenttype = kra_contenttype;
            return ((SOP_and_KRA.ServiceReference1.Service_SOPandKRASoap)(this)).Update_sopkraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOP_and_KRA.ServiceReference1.Insert_ComplianceResponse SOP_and_KRA.ServiceReference1.Service_SOPandKRASoap.Insert_Compliance(SOP_and_KRA.ServiceReference1.Insert_ComplianceRequest request) {
            return base.Channel.Insert_Compliance(request);
        }
        
        public int Insert_Compliance(string dept_id, string designation, byte[] sop_attachment, string sop_filename, string sop_contenttype, byte[] kra_attachment, string kra_filename, string kra_contenttype) {
            SOP_and_KRA.ServiceReference1.Insert_ComplianceRequest inValue = new SOP_and_KRA.ServiceReference1.Insert_ComplianceRequest();
            inValue.dept_id = dept_id;
            inValue.designation = designation;
            inValue.sop_attachment = sop_attachment;
            inValue.sop_filename = sop_filename;
            inValue.sop_contenttype = sop_contenttype;
            inValue.kra_attachment = kra_attachment;
            inValue.kra_filename = kra_filename;
            inValue.kra_contenttype = kra_contenttype;
            SOP_and_KRA.ServiceReference1.Insert_ComplianceResponse retVal = ((SOP_and_KRA.ServiceReference1.Service_SOPandKRASoap)(this)).Insert_Compliance(inValue);
            return retVal.Insert_ComplianceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOP_and_KRA.ServiceReference1.Insert_ComplianceResponse> SOP_and_KRA.ServiceReference1.Service_SOPandKRASoap.Insert_ComplianceAsync(SOP_and_KRA.ServiceReference1.Insert_ComplianceRequest request) {
            return base.Channel.Insert_ComplianceAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOP_and_KRA.ServiceReference1.Insert_ComplianceResponse> Insert_ComplianceAsync(string dept_id, string designation, byte[] sop_attachment, string sop_filename, string sop_contenttype, byte[] kra_attachment, string kra_filename, string kra_contenttype) {
            SOP_and_KRA.ServiceReference1.Insert_ComplianceRequest inValue = new SOP_and_KRA.ServiceReference1.Insert_ComplianceRequest();
            inValue.dept_id = dept_id;
            inValue.designation = designation;
            inValue.sop_attachment = sop_attachment;
            inValue.sop_filename = sop_filename;
            inValue.sop_contenttype = sop_contenttype;
            inValue.kra_attachment = kra_attachment;
            inValue.kra_filename = kra_filename;
            inValue.kra_contenttype = kra_contenttype;
            return ((SOP_and_KRA.ServiceReference1.Service_SOPandKRASoap)(this)).Insert_ComplianceAsync(inValue);
        }
    }
}
