//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Application.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService_CRMSoap")]
    public interface WebService_CRMSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_login", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_loginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_NewBooking", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Insert_NewBooking(int BranchID, int DeptID, int DoctorID, string BookDate, string VisitTime, string PatientName, string Phone, string Token, string CreatedBy, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_NewBooking", ReplyAction="*")]
        System.Threading.Tasks.Task<int> Insert_NewBookingAsync(int BranchID, int DeptID, int DoctorID, string BookDate, string VisitTime, string PatientName, string Phone, string Token, string CreatedBy, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_Doctor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Insert_Doctor(int DoctorID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_Doctor", ReplyAction="*")]
        System.Threading.Tasks.Task<int> Insert_DoctorAsync(int DoctorID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_RescheduledBooking", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Insert_RescheduledBooking(int Booking_Id, int BranchID, int DeptID, int DoctorID, string BookDate, string VisitTime, string PatientName, string Phone, string Token, string CreatedBy, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_RescheduledBooking", ReplyAction="*")]
        System.Threading.Tasks.Task<int> Insert_RescheduledBookingAsync(int Booking_Id, int BranchID, int DeptID, int DoctorID, string BookDate, string VisitTime, string PatientName, string Phone, string Token, string CreatedBy, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_CRMBooking", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Update_CRMBooking(int Booking_id, int BranchID, int DeptID, int DoctorID, string BookDate, string VisitTime, string PatientName, string Phone, string Token, string CreatedBy, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_CRMBooking", ReplyAction="*")]
        System.Threading.Tasks.Task<int> Update_CRMBookingAsync(int Booking_id, int BranchID, int DeptID, int DoctorID, string BookDate, string VisitTime, string PatientName, string Phone, string Token, string CreatedBy, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_Bookingdtl", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Update_Bookingdtl(int Booking_id, string PatientName, string Phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_Bookingdtl", ReplyAction="*")]
        System.Threading.Tasks.Task<int> Update_BookingdtlAsync(int Booking_id, string PatientName, string Phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_BookingStatus_Arrived", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Update_BookingStatus_Arrived(int Booking_id, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_BookingStatus_Arrived", ReplyAction="*")]
        System.Threading.Tasks.Task<int> Update_BookingStatus_ArrivedAsync(int Booking_id, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_BookingStatus_Confirm", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Update_BookingStatus_Confirm(int Booking_id, string confirmby, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_BookingStatus_Confirm", ReplyAction="*")]
        System.Threading.Tasks.Task<int> Update_BookingStatus_ConfirmAsync(int Booking_id, string confirmby, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_BookingStatus_Cancel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Add_BookingStatus_Cancel(int Booking_id, string Reason_ForCancel, string cancelledby);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_BookingStatus_Cancel", ReplyAction="*")]
        System.Threading.Tasks.Task<int> Add_BookingStatus_CancelAsync(int Booking_id, string Reason_ForCancel, string cancelledby);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_BookingStatus_Reschedule", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Add_BookingStatus_Reschedule(int Booking_id, string Reason_ForCancel, string cancelledby);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_BookingStatus_Reschedule", ReplyAction="*")]
        System.Threading.Tasks.Task<int> Add_BookingStatus_RescheduleAsync(int Booking_id, string Reason_ForCancel, string cancelledby);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Branch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Branch();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Branch", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_BranchAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Registereddoctors", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Registereddoctors(int branchid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Registereddoctors", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_RegistereddoctorsAsync(int branchid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/delete_select", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet delete_select(int drid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/delete_select", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> delete_selectAsync(int drid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Department", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Department();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Department", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_DepartmentAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Doctor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Doctor(int branch_id, int dept_id, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Doctor", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_DoctorAsync(int branch_id, int dept_id, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Doctor1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Doctor1(int dept_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Doctor1", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_Doctor1Async(int dept_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Doctorfrmdrrreg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Doctorfrmdrrreg(int branch_id, int dept_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Doctorfrmdrrreg", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_DoctorfrmdrrregAsync(int branch_id, int dept_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Doctorattendance_avail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Doctorattendance_avail(string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Doctorattendance_avail", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_Doctorattendance_availAsync(string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Doctor_availability", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Doctor_availability(int branch_id, int dept_id, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Doctor_availability", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_Doctor_availabilityAsync(int branch_id, int dept_id, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Doctor_availabilityattend", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Doctor_availabilityattend(int branch_id, int dept_id, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Doctor_availabilityattend", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_Doctor_availabilityattendAsync(int branch_id, int dept_id, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Doctor_departmentforconfirmation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Doctor_departmentforconfirmation(int branch_id, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Doctor_departmentforconfirmation", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_Doctor_departmentforconfirmationAsync(int branch_id, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Report", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Report(int branch_id, string date1, string date2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Report", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_ReportAsync(int branch_id, string date1, string date2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_NextToken", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_NextToken(int branch_id, int dept_id, int doctor_id, string date_);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_NextToken", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_NextTokenAsync(int branch_id, int dept_id, int doctor_id, string date_);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_VisitTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_VisitTime(int branch_id, int dept_id, int doctor_id, string date_);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_VisitTime", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_VisitTimeAsync(int branch_id, int dept_id, int doctor_id, string date_);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_BookingDtlstoreschedule", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_BookingDtlstoreschedule(int booking_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_BookingDtlstoreschedule", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_BookingDtlstorescheduleAsync(int booking_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_BookingDtls_forconsultationstatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_BookingDtls_forconsultationstatus(int branch_id, int dr_id, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_BookingDtls_forconsultationstatus", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_BookingDtls_forconsultationstatusAsync(int branch_id, int dr_id, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_BookingDtls_forconfirmation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_BookingDtls_forconfirmation(int branch_id, int dr_id, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_BookingDtls_forconfirmation", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_BookingDtls_forconfirmationAsync(int branch_id, int dr_id, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_BookingDtls_foredit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_BookingDtls_foredit(int branch_id, int dr_id, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_BookingDtls_foredit", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_BookingDtls_foreditAsync(int branch_id, int dr_id, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_BookingDtls", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_BookingDtls(int branch_id, int dept_id, int dr_id, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_BookingDtls", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_BookingDtlsAsync(int branch_id, int dept_id, int dr_id, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_BookingDtls_Todaybooking", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_BookingDtls_Todaybooking(int branch_id, int dept_id, int dr_id, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_BookingDtls_Todaybooking", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_BookingDtls_TodaybookingAsync(int branch_id, int dept_id, int dr_id, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Report_Todaybooking", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Report_Todaybooking(int branch_id, int dept_id, int dr_id, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Report_Todaybooking", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_Report_TodaybookingAsync(int branch_id, int dept_id, int dr_id, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_PatientDtls", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_PatientDtls(int branch_id, int dept_id, int doctor_id, string date_, string visit_time);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_PatientDtls", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_PatientDtlsAsync(int branch_id, int dept_id, int doctor_id, string date_, string visit_time);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_BookingReport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_BookingReport(int branch_id, int dept_id, int doctor_id, string date_, string visit_time, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_BookingReport", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_BookingReportAsync(int branch_id, int dept_id, int doctor_id, string date_, string visit_time, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_Usage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Insert_Usage(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_Usage", ReplyAction="*")]
        System.Threading.Tasks.Task<int> Insert_UsageAsync(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService_CRMSoapChannel : CRM_Application.ServiceReference1.WebService_CRMSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService_CRMSoapClient : System.ServiceModel.ClientBase<CRM_Application.ServiceReference1.WebService_CRMSoap>, CRM_Application.ServiceReference1.WebService_CRMSoap {
        
        public WebService_CRMSoapClient() {
        }
        
        public WebService_CRMSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService_CRMSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_CRMSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_CRMSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public System.Data.DataSet Get_login(string username, string password) {
            return base.Channel.Get_login(username, password);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_loginAsync(string username, string password) {
            return base.Channel.Get_loginAsync(username, password);
        }
        
        public int Insert_NewBooking(int BranchID, int DeptID, int DoctorID, string BookDate, string VisitTime, string PatientName, string Phone, string Token, string CreatedBy, string status) {
            return base.Channel.Insert_NewBooking(BranchID, DeptID, DoctorID, BookDate, VisitTime, PatientName, Phone, Token, CreatedBy, status);
        }
        
        public System.Threading.Tasks.Task<int> Insert_NewBookingAsync(int BranchID, int DeptID, int DoctorID, string BookDate, string VisitTime, string PatientName, string Phone, string Token, string CreatedBy, string status) {
            return base.Channel.Insert_NewBookingAsync(BranchID, DeptID, DoctorID, BookDate, VisitTime, PatientName, Phone, Token, CreatedBy, status);
        }
        
        public int Insert_Doctor(int DoctorID) {
            return base.Channel.Insert_Doctor(DoctorID);
        }
        
        public System.Threading.Tasks.Task<int> Insert_DoctorAsync(int DoctorID) {
            return base.Channel.Insert_DoctorAsync(DoctorID);
        }
        
        public int Insert_RescheduledBooking(int Booking_Id, int BranchID, int DeptID, int DoctorID, string BookDate, string VisitTime, string PatientName, string Phone, string Token, string CreatedBy, string status) {
            return base.Channel.Insert_RescheduledBooking(Booking_Id, BranchID, DeptID, DoctorID, BookDate, VisitTime, PatientName, Phone, Token, CreatedBy, status);
        }
        
        public System.Threading.Tasks.Task<int> Insert_RescheduledBookingAsync(int Booking_Id, int BranchID, int DeptID, int DoctorID, string BookDate, string VisitTime, string PatientName, string Phone, string Token, string CreatedBy, string status) {
            return base.Channel.Insert_RescheduledBookingAsync(Booking_Id, BranchID, DeptID, DoctorID, BookDate, VisitTime, PatientName, Phone, Token, CreatedBy, status);
        }
        
        public int Update_CRMBooking(int Booking_id, int BranchID, int DeptID, int DoctorID, string BookDate, string VisitTime, string PatientName, string Phone, string Token, string CreatedBy, string status) {
            return base.Channel.Update_CRMBooking(Booking_id, BranchID, DeptID, DoctorID, BookDate, VisitTime, PatientName, Phone, Token, CreatedBy, status);
        }
        
        public System.Threading.Tasks.Task<int> Update_CRMBookingAsync(int Booking_id, int BranchID, int DeptID, int DoctorID, string BookDate, string VisitTime, string PatientName, string Phone, string Token, string CreatedBy, string status) {
            return base.Channel.Update_CRMBookingAsync(Booking_id, BranchID, DeptID, DoctorID, BookDate, VisitTime, PatientName, Phone, Token, CreatedBy, status);
        }
        
        public int Update_Bookingdtl(int Booking_id, string PatientName, string Phone) {
            return base.Channel.Update_Bookingdtl(Booking_id, PatientName, Phone);
        }
        
        public System.Threading.Tasks.Task<int> Update_BookingdtlAsync(int Booking_id, string PatientName, string Phone) {
            return base.Channel.Update_BookingdtlAsync(Booking_id, PatientName, Phone);
        }
        
        public int Update_BookingStatus_Arrived(int Booking_id, string status) {
            return base.Channel.Update_BookingStatus_Arrived(Booking_id, status);
        }
        
        public System.Threading.Tasks.Task<int> Update_BookingStatus_ArrivedAsync(int Booking_id, string status) {
            return base.Channel.Update_BookingStatus_ArrivedAsync(Booking_id, status);
        }
        
        public int Update_BookingStatus_Confirm(int Booking_id, string confirmby, string status) {
            return base.Channel.Update_BookingStatus_Confirm(Booking_id, confirmby, status);
        }
        
        public System.Threading.Tasks.Task<int> Update_BookingStatus_ConfirmAsync(int Booking_id, string confirmby, string status) {
            return base.Channel.Update_BookingStatus_ConfirmAsync(Booking_id, confirmby, status);
        }
        
        public int Add_BookingStatus_Cancel(int Booking_id, string Reason_ForCancel, string cancelledby) {
            return base.Channel.Add_BookingStatus_Cancel(Booking_id, Reason_ForCancel, cancelledby);
        }
        
        public System.Threading.Tasks.Task<int> Add_BookingStatus_CancelAsync(int Booking_id, string Reason_ForCancel, string cancelledby) {
            return base.Channel.Add_BookingStatus_CancelAsync(Booking_id, Reason_ForCancel, cancelledby);
        }
        
        public int Add_BookingStatus_Reschedule(int Booking_id, string Reason_ForCancel, string cancelledby) {
            return base.Channel.Add_BookingStatus_Reschedule(Booking_id, Reason_ForCancel, cancelledby);
        }
        
        public System.Threading.Tasks.Task<int> Add_BookingStatus_RescheduleAsync(int Booking_id, string Reason_ForCancel, string cancelledby) {
            return base.Channel.Add_BookingStatus_RescheduleAsync(Booking_id, Reason_ForCancel, cancelledby);
        }
        
        public System.Data.DataSet Get_Branch() {
            return base.Channel.Get_Branch();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_BranchAsync() {
            return base.Channel.Get_BranchAsync();
        }
        
        public System.Data.DataSet Get_Registereddoctors(int branchid) {
            return base.Channel.Get_Registereddoctors(branchid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_RegistereddoctorsAsync(int branchid) {
            return base.Channel.Get_RegistereddoctorsAsync(branchid);
        }
        
        public System.Data.DataSet delete_select(int drid) {
            return base.Channel.delete_select(drid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> delete_selectAsync(int drid) {
            return base.Channel.delete_selectAsync(drid);
        }
        
        public System.Data.DataSet Get_Department() {
            return base.Channel.Get_Department();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_DepartmentAsync() {
            return base.Channel.Get_DepartmentAsync();
        }
        
        public System.Data.DataSet Get_Doctor(int branch_id, int dept_id, string date) {
            return base.Channel.Get_Doctor(branch_id, dept_id, date);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_DoctorAsync(int branch_id, int dept_id, string date) {
            return base.Channel.Get_DoctorAsync(branch_id, dept_id, date);
        }
        
        public System.Data.DataSet Get_Doctor1(int dept_id) {
            return base.Channel.Get_Doctor1(dept_id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_Doctor1Async(int dept_id) {
            return base.Channel.Get_Doctor1Async(dept_id);
        }
        
        public System.Data.DataSet Get_Doctorfrmdrrreg(int branch_id, int dept_id) {
            return base.Channel.Get_Doctorfrmdrrreg(branch_id, dept_id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_DoctorfrmdrrregAsync(int branch_id, int dept_id) {
            return base.Channel.Get_DoctorfrmdrrregAsync(branch_id, dept_id);
        }
        
        public System.Data.DataSet Get_Doctorattendance_avail(string date) {
            return base.Channel.Get_Doctorattendance_avail(date);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_Doctorattendance_availAsync(string date) {
            return base.Channel.Get_Doctorattendance_availAsync(date);
        }
        
        public System.Data.DataSet Get_Doctor_availability(int branch_id, int dept_id, string date) {
            return base.Channel.Get_Doctor_availability(branch_id, dept_id, date);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_Doctor_availabilityAsync(int branch_id, int dept_id, string date) {
            return base.Channel.Get_Doctor_availabilityAsync(branch_id, dept_id, date);
        }
        
        public System.Data.DataSet Get_Doctor_availabilityattend(int branch_id, int dept_id, string date) {
            return base.Channel.Get_Doctor_availabilityattend(branch_id, dept_id, date);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_Doctor_availabilityattendAsync(int branch_id, int dept_id, string date) {
            return base.Channel.Get_Doctor_availabilityattendAsync(branch_id, dept_id, date);
        }
        
        public System.Data.DataSet Get_Doctor_departmentforconfirmation(int branch_id, string date) {
            return base.Channel.Get_Doctor_departmentforconfirmation(branch_id, date);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_Doctor_departmentforconfirmationAsync(int branch_id, string date) {
            return base.Channel.Get_Doctor_departmentforconfirmationAsync(branch_id, date);
        }
        
        public System.Data.DataSet Get_Report(int branch_id, string date1, string date2) {
            return base.Channel.Get_Report(branch_id, date1, date2);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_ReportAsync(int branch_id, string date1, string date2) {
            return base.Channel.Get_ReportAsync(branch_id, date1, date2);
        }
        
        public System.Data.DataSet Get_NextToken(int branch_id, int dept_id, int doctor_id, string date_) {
            return base.Channel.Get_NextToken(branch_id, dept_id, doctor_id, date_);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_NextTokenAsync(int branch_id, int dept_id, int doctor_id, string date_) {
            return base.Channel.Get_NextTokenAsync(branch_id, dept_id, doctor_id, date_);
        }
        
        public System.Data.DataSet Get_VisitTime(int branch_id, int dept_id, int doctor_id, string date_) {
            return base.Channel.Get_VisitTime(branch_id, dept_id, doctor_id, date_);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_VisitTimeAsync(int branch_id, int dept_id, int doctor_id, string date_) {
            return base.Channel.Get_VisitTimeAsync(branch_id, dept_id, doctor_id, date_);
        }
        
        public System.Data.DataSet Get_BookingDtlstoreschedule(int booking_id) {
            return base.Channel.Get_BookingDtlstoreschedule(booking_id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_BookingDtlstorescheduleAsync(int booking_id) {
            return base.Channel.Get_BookingDtlstorescheduleAsync(booking_id);
        }
        
        public System.Data.DataSet Get_BookingDtls_forconsultationstatus(int branch_id, int dr_id, string date) {
            return base.Channel.Get_BookingDtls_forconsultationstatus(branch_id, dr_id, date);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_BookingDtls_forconsultationstatusAsync(int branch_id, int dr_id, string date) {
            return base.Channel.Get_BookingDtls_forconsultationstatusAsync(branch_id, dr_id, date);
        }
        
        public System.Data.DataSet Get_BookingDtls_forconfirmation(int branch_id, int dr_id, string date) {
            return base.Channel.Get_BookingDtls_forconfirmation(branch_id, dr_id, date);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_BookingDtls_forconfirmationAsync(int branch_id, int dr_id, string date) {
            return base.Channel.Get_BookingDtls_forconfirmationAsync(branch_id, dr_id, date);
        }
        
        public System.Data.DataSet Get_BookingDtls_foredit(int branch_id, int dr_id, string date) {
            return base.Channel.Get_BookingDtls_foredit(branch_id, dr_id, date);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_BookingDtls_foreditAsync(int branch_id, int dr_id, string date) {
            return base.Channel.Get_BookingDtls_foreditAsync(branch_id, dr_id, date);
        }
        
        public System.Data.DataSet Get_BookingDtls(int branch_id, int dept_id, int dr_id, string date) {
            return base.Channel.Get_BookingDtls(branch_id, dept_id, dr_id, date);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_BookingDtlsAsync(int branch_id, int dept_id, int dr_id, string date) {
            return base.Channel.Get_BookingDtlsAsync(branch_id, dept_id, dr_id, date);
        }
        
        public System.Data.DataSet Get_BookingDtls_Todaybooking(int branch_id, int dept_id, int dr_id, string date) {
            return base.Channel.Get_BookingDtls_Todaybooking(branch_id, dept_id, dr_id, date);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_BookingDtls_TodaybookingAsync(int branch_id, int dept_id, int dr_id, string date) {
            return base.Channel.Get_BookingDtls_TodaybookingAsync(branch_id, dept_id, dr_id, date);
        }
        
        public System.Data.DataSet Get_Report_Todaybooking(int branch_id, int dept_id, int dr_id, string date) {
            return base.Channel.Get_Report_Todaybooking(branch_id, dept_id, dr_id, date);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_Report_TodaybookingAsync(int branch_id, int dept_id, int dr_id, string date) {
            return base.Channel.Get_Report_TodaybookingAsync(branch_id, dept_id, dr_id, date);
        }
        
        public System.Data.DataSet Get_PatientDtls(int branch_id, int dept_id, int doctor_id, string date_, string visit_time) {
            return base.Channel.Get_PatientDtls(branch_id, dept_id, doctor_id, date_, visit_time);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_PatientDtlsAsync(int branch_id, int dept_id, int doctor_id, string date_, string visit_time) {
            return base.Channel.Get_PatientDtlsAsync(branch_id, dept_id, doctor_id, date_, visit_time);
        }
        
        public System.Data.DataSet Get_BookingReport(int branch_id, int dept_id, int doctor_id, string date_, string visit_time, string type) {
            return base.Channel.Get_BookingReport(branch_id, dept_id, doctor_id, date_, visit_time, type);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_BookingReportAsync(int branch_id, int dept_id, int doctor_id, string date_, string visit_time, string type) {
            return base.Channel.Get_BookingReportAsync(branch_id, dept_id, doctor_id, date_, visit_time, type);
        }
        
        public int Insert_Usage(string username) {
            return base.Channel.Insert_Usage(username);
        }
        
        public System.Threading.Tasks.Task<int> Insert_UsageAsync(string username) {
            return base.Channel.Insert_UsageAsync(username);
        }
    }
}
