//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRF_Tracker_Latest.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService_CRFTrackerSoap")]
    public interface WebService_CRFTrackerSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Login(string u_name, string pswd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> LoginAsync(string u_name, string pswd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_CrfId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_CrfId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_CrfId", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_CrfIdAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_NewCrf", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Insert_NewCrf(string crf_id, string crf_name, string crf_description, string req_type, string priority, string crf_scope, string reference_name, string requestor_id, string requestor_name, string status, string designation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_NewCrf", ReplyAction="*")]
        System.Threading.Tasks.Task<int> Insert_NewCrfAsync(string crf_id, string crf_name, string crf_description, string req_type, string priority, string crf_scope, string reference_name, string requestor_id, string requestor_name, string status, string designation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Crf", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Crf();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Crf", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_CrfAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Crf_WithotId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Crf_WithotId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Crf_WithotId", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_Crf_WithotIdAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_CrfwithId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_CrfwithId(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_CrfwithId", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_CrfwithIdAsync(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_CrfDtls", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_CrfDtls(string crfid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_CrfDtls", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_CrfDtlsAsync(string crfid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Crf_forRecommend", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Crf_forRecommend();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Crf_forRecommend", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_Crf_forRecommendAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_CrfRecommend", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_CrfRecommend();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_CrfRecommend", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_CrfRecommendAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Crf_forApprove", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Crf_forApprove();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Crf_forApprove", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_Crf_forApproveAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_CrfApprove", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_CrfApprove();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_CrfApprove", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_CrfApproveAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Crf_forTA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Crf_forTA();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Crf_forTA", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_Crf_forTAAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_ta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_ta(string crfid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_ta", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_taAsync(string crfid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Crfforaddta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Crfforaddta();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Crfforaddta", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_CrfforaddtaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_CRFwithTA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Update_CRFwithTA(string crfid, string dev_startdate, string dev_enddate, string target_date, string manhours, string QA_startdate, string QA_enddate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_CRFwithTA", ReplyAction="*")]
        System.Threading.Tasks.Task<int> Update_CRFwithTAAsync(string crfid, string dev_startdate, string dev_enddate, string target_date, string manhours, string QA_startdate, string QA_enddate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_developers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_developers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_developers", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_developersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_TA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Update_TA(int TA_id, string phase, string taskname, string manhours, string startdate, string enddate, string developer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_TA", ReplyAction="*")]
        System.Threading.Tasks.Task<int> Update_TAAsync(int TA_id, string phase, string taskname, string manhours, string startdate, string enddate, string developer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete_TA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Delete_TA(int TA_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete_TA", ReplyAction="*")]
        System.Threading.Tasks.Task<int> Delete_TAAsync(int TA_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_ta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Insert_ta(string crf_id, string phase, string taskname, string manhours, string start_date, string end_date, string developer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_ta", ReplyAction="*")]
        System.Threading.Tasks.Task<int> Insert_taAsync(string crf_id, string phase, string taskname, string manhours, string start_date, string end_date, string developer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/View_tamaster", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet View_tamaster(string crfid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/View_tamaster", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> View_tamasterAsync(string crfid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/View_ta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet View_ta(string crfid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/View_ta", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> View_taAsync(string crfid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Crfforstatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Crfforstatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Crfforstatus", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_CrfforstatusAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_Crfstatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Update_Crfstatus(string crf_id, string crf_status, string curr_date, string remarks, string dly_status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_Crfstatus", ReplyAction="*")]
        System.Threading.Tasks.Task<int> Update_CrfstatusAsync(string crf_id, string crf_status, string curr_date, string remarks, string dly_status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_Approve_reject", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Update_Approve_reject(string crf_id, string remarks, string status, string userid, string usertype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_Approve_reject", ReplyAction="*")]
        System.Threading.Tasks.Task<int> Update_Approve_rejectAsync(string crf_id, string remarks, string status, string userid, string usertype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_Tastatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Update_Tastatus(string crf_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_Tastatus", ReplyAction="*")]
        System.Threading.Tasks.Task<int> Update_TastatusAsync(string crf_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_CRFreport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_CRFreport(string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_CRFreport", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_CRFreportAsync(string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Crf_count", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Crf_count();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Crf_count", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_Crf_countAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_designation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_designation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_designation", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_designationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_users", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_users(string designation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_users", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_usersAsync(string designation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_TicketId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_TicketId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_TicketId", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_TicketIdAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_NewTicket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Insert_NewTicket(int ticket_no, string issued_by, string issue_detail, string ticket_type, string crf_desc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_NewTicket", ReplyAction="*")]
        System.Threading.Tasks.Task<int> Insert_NewTicketAsync(int ticket_no, string issued_by, string issue_detail, string ticket_type, string crf_desc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Tickets", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Tickets(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Tickets", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_TicketsAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Tickets_Dashboard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Tickets_Dashboard(string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Tickets_Dashboard", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_Tickets_DashboardAsync(string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_ticket_forApprove", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_ticket_forApprove();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_ticket_forApprove", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_ticket_forApproveAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_ticket_forResolve", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_ticket_forResolve();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_ticket_forResolve", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_ticket_forResolveAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_ticket_forResolve_byId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_ticket_forResolve_byId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_ticket_forResolve_byId", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_ticket_forResolve_byIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_Resolvestatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Update_Resolvestatus(int ticket_no, string resolve_status, string resolved_by, string remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_Resolvestatus", ReplyAction="*")]
        System.Threading.Tasks.Task<int> Update_ResolvestatusAsync(int ticket_no, string resolve_status, string resolved_by, string remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_Approvestatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Update_Approvestatus(int ticket_no, string Approve_status, string Approved_by);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_Approvestatus", ReplyAction="*")]
        System.Threading.Tasks.Task<int> Update_ApprovestatusAsync(int ticket_no, string Approve_status, string Approved_by);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService_CRFTrackerSoapChannel : CRF_Tracker_Latest.ServiceReference1.WebService_CRFTrackerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService_CRFTrackerSoapClient : System.ServiceModel.ClientBase<CRF_Tracker_Latest.ServiceReference1.WebService_CRFTrackerSoap>, CRF_Tracker_Latest.ServiceReference1.WebService_CRFTrackerSoap {
        
        public WebService_CRFTrackerSoapClient() {
        }
        
        public WebService_CRFTrackerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService_CRFTrackerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_CRFTrackerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_CRFTrackerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public System.Data.DataSet Login(string u_name, string pswd) {
            return base.Channel.Login(u_name, pswd);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> LoginAsync(string u_name, string pswd) {
            return base.Channel.LoginAsync(u_name, pswd);
        }
        
        public System.Data.DataSet Get_CrfId() {
            return base.Channel.Get_CrfId();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_CrfIdAsync() {
            return base.Channel.Get_CrfIdAsync();
        }
        
        public int Insert_NewCrf(string crf_id, string crf_name, string crf_description, string req_type, string priority, string crf_scope, string reference_name, string requestor_id, string requestor_name, string status, string designation) {
            return base.Channel.Insert_NewCrf(crf_id, crf_name, crf_description, req_type, priority, crf_scope, reference_name, requestor_id, requestor_name, status, designation);
        }
        
        public System.Threading.Tasks.Task<int> Insert_NewCrfAsync(string crf_id, string crf_name, string crf_description, string req_type, string priority, string crf_scope, string reference_name, string requestor_id, string requestor_name, string status, string designation) {
            return base.Channel.Insert_NewCrfAsync(crf_id, crf_name, crf_description, req_type, priority, crf_scope, reference_name, requestor_id, requestor_name, status, designation);
        }
        
        public System.Data.DataSet Get_Crf() {
            return base.Channel.Get_Crf();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_CrfAsync() {
            return base.Channel.Get_CrfAsync();
        }
        
        public System.Data.DataSet Get_Crf_WithotId() {
            return base.Channel.Get_Crf_WithotId();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_Crf_WithotIdAsync() {
            return base.Channel.Get_Crf_WithotIdAsync();
        }
        
        public System.Data.DataSet Get_CrfwithId(string category) {
            return base.Channel.Get_CrfwithId(category);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_CrfwithIdAsync(string category) {
            return base.Channel.Get_CrfwithIdAsync(category);
        }
        
        public System.Data.DataSet Get_CrfDtls(string crfid) {
            return base.Channel.Get_CrfDtls(crfid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_CrfDtlsAsync(string crfid) {
            return base.Channel.Get_CrfDtlsAsync(crfid);
        }
        
        public System.Data.DataSet Get_Crf_forRecommend() {
            return base.Channel.Get_Crf_forRecommend();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_Crf_forRecommendAsync() {
            return base.Channel.Get_Crf_forRecommendAsync();
        }
        
        public System.Data.DataSet Get_CrfRecommend() {
            return base.Channel.Get_CrfRecommend();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_CrfRecommendAsync() {
            return base.Channel.Get_CrfRecommendAsync();
        }
        
        public System.Data.DataSet Get_Crf_forApprove() {
            return base.Channel.Get_Crf_forApprove();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_Crf_forApproveAsync() {
            return base.Channel.Get_Crf_forApproveAsync();
        }
        
        public System.Data.DataSet Get_CrfApprove() {
            return base.Channel.Get_CrfApprove();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_CrfApproveAsync() {
            return base.Channel.Get_CrfApproveAsync();
        }
        
        public System.Data.DataSet Get_Crf_forTA() {
            return base.Channel.Get_Crf_forTA();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_Crf_forTAAsync() {
            return base.Channel.Get_Crf_forTAAsync();
        }
        
        public System.Data.DataSet Get_ta(string crfid) {
            return base.Channel.Get_ta(crfid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_taAsync(string crfid) {
            return base.Channel.Get_taAsync(crfid);
        }
        
        public System.Data.DataSet Get_Crfforaddta() {
            return base.Channel.Get_Crfforaddta();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_CrfforaddtaAsync() {
            return base.Channel.Get_CrfforaddtaAsync();
        }
        
        public int Update_CRFwithTA(string crfid, string dev_startdate, string dev_enddate, string target_date, string manhours, string QA_startdate, string QA_enddate) {
            return base.Channel.Update_CRFwithTA(crfid, dev_startdate, dev_enddate, target_date, manhours, QA_startdate, QA_enddate);
        }
        
        public System.Threading.Tasks.Task<int> Update_CRFwithTAAsync(string crfid, string dev_startdate, string dev_enddate, string target_date, string manhours, string QA_startdate, string QA_enddate) {
            return base.Channel.Update_CRFwithTAAsync(crfid, dev_startdate, dev_enddate, target_date, manhours, QA_startdate, QA_enddate);
        }
        
        public System.Data.DataSet Get_developers() {
            return base.Channel.Get_developers();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_developersAsync() {
            return base.Channel.Get_developersAsync();
        }
        
        public int Update_TA(int TA_id, string phase, string taskname, string manhours, string startdate, string enddate, string developer) {
            return base.Channel.Update_TA(TA_id, phase, taskname, manhours, startdate, enddate, developer);
        }
        
        public System.Threading.Tasks.Task<int> Update_TAAsync(int TA_id, string phase, string taskname, string manhours, string startdate, string enddate, string developer) {
            return base.Channel.Update_TAAsync(TA_id, phase, taskname, manhours, startdate, enddate, developer);
        }
        
        public int Delete_TA(int TA_id) {
            return base.Channel.Delete_TA(TA_id);
        }
        
        public System.Threading.Tasks.Task<int> Delete_TAAsync(int TA_id) {
            return base.Channel.Delete_TAAsync(TA_id);
        }
        
        public int Insert_ta(string crf_id, string phase, string taskname, string manhours, string start_date, string end_date, string developer) {
            return base.Channel.Insert_ta(crf_id, phase, taskname, manhours, start_date, end_date, developer);
        }
        
        public System.Threading.Tasks.Task<int> Insert_taAsync(string crf_id, string phase, string taskname, string manhours, string start_date, string end_date, string developer) {
            return base.Channel.Insert_taAsync(crf_id, phase, taskname, manhours, start_date, end_date, developer);
        }
        
        public System.Data.DataSet View_tamaster(string crfid) {
            return base.Channel.View_tamaster(crfid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> View_tamasterAsync(string crfid) {
            return base.Channel.View_tamasterAsync(crfid);
        }
        
        public System.Data.DataSet View_ta(string crfid) {
            return base.Channel.View_ta(crfid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> View_taAsync(string crfid) {
            return base.Channel.View_taAsync(crfid);
        }
        
        public System.Data.DataSet Get_Crfforstatus() {
            return base.Channel.Get_Crfforstatus();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_CrfforstatusAsync() {
            return base.Channel.Get_CrfforstatusAsync();
        }
        
        public int Update_Crfstatus(string crf_id, string crf_status, string curr_date, string remarks, string dly_status) {
            return base.Channel.Update_Crfstatus(crf_id, crf_status, curr_date, remarks, dly_status);
        }
        
        public System.Threading.Tasks.Task<int> Update_CrfstatusAsync(string crf_id, string crf_status, string curr_date, string remarks, string dly_status) {
            return base.Channel.Update_CrfstatusAsync(crf_id, crf_status, curr_date, remarks, dly_status);
        }
        
        public int Update_Approve_reject(string crf_id, string remarks, string status, string userid, string usertype) {
            return base.Channel.Update_Approve_reject(crf_id, remarks, status, userid, usertype);
        }
        
        public System.Threading.Tasks.Task<int> Update_Approve_rejectAsync(string crf_id, string remarks, string status, string userid, string usertype) {
            return base.Channel.Update_Approve_rejectAsync(crf_id, remarks, status, userid, usertype);
        }
        
        public int Update_Tastatus(string crf_id) {
            return base.Channel.Update_Tastatus(crf_id);
        }
        
        public System.Threading.Tasks.Task<int> Update_TastatusAsync(string crf_id) {
            return base.Channel.Update_TastatusAsync(crf_id);
        }
        
        public System.Data.DataSet Get_CRFreport(string status) {
            return base.Channel.Get_CRFreport(status);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_CRFreportAsync(string status) {
            return base.Channel.Get_CRFreportAsync(status);
        }
        
        public System.Data.DataSet Get_Crf_count() {
            return base.Channel.Get_Crf_count();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_Crf_countAsync() {
            return base.Channel.Get_Crf_countAsync();
        }
        
        public System.Data.DataSet Get_designation() {
            return base.Channel.Get_designation();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_designationAsync() {
            return base.Channel.Get_designationAsync();
        }
        
        public System.Data.DataSet Get_users(string designation) {
            return base.Channel.Get_users(designation);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_usersAsync(string designation) {
            return base.Channel.Get_usersAsync(designation);
        }
        
        public System.Data.DataSet Get_TicketId() {
            return base.Channel.Get_TicketId();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_TicketIdAsync() {
            return base.Channel.Get_TicketIdAsync();
        }
        
        public int Insert_NewTicket(int ticket_no, string issued_by, string issue_detail, string ticket_type, string crf_desc) {
            return base.Channel.Insert_NewTicket(ticket_no, issued_by, issue_detail, ticket_type, crf_desc);
        }
        
        public System.Threading.Tasks.Task<int> Insert_NewTicketAsync(int ticket_no, string issued_by, string issue_detail, string ticket_type, string crf_desc) {
            return base.Channel.Insert_NewTicketAsync(ticket_no, issued_by, issue_detail, ticket_type, crf_desc);
        }
        
        public System.Data.DataSet Get_Tickets(int id) {
            return base.Channel.Get_Tickets(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_TicketsAsync(int id) {
            return base.Channel.Get_TicketsAsync(id);
        }
        
        public System.Data.DataSet Get_Tickets_Dashboard(string type) {
            return base.Channel.Get_Tickets_Dashboard(type);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_Tickets_DashboardAsync(string type) {
            return base.Channel.Get_Tickets_DashboardAsync(type);
        }
        
        public System.Data.DataSet Get_ticket_forApprove() {
            return base.Channel.Get_ticket_forApprove();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_ticket_forApproveAsync() {
            return base.Channel.Get_ticket_forApproveAsync();
        }
        
        public System.Data.DataSet Get_ticket_forResolve() {
            return base.Channel.Get_ticket_forResolve();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_ticket_forResolveAsync() {
            return base.Channel.Get_ticket_forResolveAsync();
        }
        
        public System.Data.DataSet Get_ticket_forResolve_byId(int id) {
            return base.Channel.Get_ticket_forResolve_byId(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_ticket_forResolve_byIdAsync(int id) {
            return base.Channel.Get_ticket_forResolve_byIdAsync(id);
        }
        
        public int Update_Resolvestatus(int ticket_no, string resolve_status, string resolved_by, string remarks) {
            return base.Channel.Update_Resolvestatus(ticket_no, resolve_status, resolved_by, remarks);
        }
        
        public System.Threading.Tasks.Task<int> Update_ResolvestatusAsync(int ticket_no, string resolve_status, string resolved_by, string remarks) {
            return base.Channel.Update_ResolvestatusAsync(ticket_no, resolve_status, resolved_by, remarks);
        }
        
        public int Update_Approvestatus(int ticket_no, string Approve_status, string Approved_by) {
            return base.Channel.Update_Approvestatus(ticket_no, Approve_status, Approved_by);
        }
        
        public System.Threading.Tasks.Task<int> Update_ApprovestatusAsync(int ticket_no, string Approve_status, string Approved_by) {
            return base.Channel.Update_ApprovestatusAsync(ticket_no, Approve_status, Approved_by);
        }
    }
}
