//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compliance_Register.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService_Compliance_RegisterSoap")]
    public interface WebService_Compliance_RegisterSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_login", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_loginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_depertment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_depertment();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_depertment", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_depertmentAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_grid", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_grid();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_grid", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_gridAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_gridbyid", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_gridbyid(int dept_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_gridbyid", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_gridbyidAsync(int dept_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmpNames", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] GetEmpNames(string empcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmpNames", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> GetEmpNamesAsync(string empcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_empcode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_empcode(string empcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_empcode", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_empcodeAsync(string empcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_Compliance_Reg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Insert_Compliance_Reg(int dept_id, string dept_head, int status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_Compliance_Reg", ReplyAction="*")]
        System.Threading.Tasks.Task<int> Insert_Compliance_RegAsync(int dept_id, string dept_head, int status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_Compliance_Calendar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Insert_Compliance_Calendar(int dept_id, string Com_type, string Comp_Description, string duratn_type, string due_date, string alert_date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_Compliance_Calendar", ReplyAction="*")]
        System.Threading.Tasks.Task<int> Insert_Compliance_CalendarAsync(int dept_id, string Com_type, string Comp_Description, string duratn_type, string due_date, string alert_date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_grid_Calendar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_grid_Calendar(int dept_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_grid_Calendar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_grid_CalendarAsync(int dept_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_Compliance_Calendar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Update_Compliance_Calendar(int com_id, int dept_id, string Com_type, string Comp_Description, string duratn_type, string due_date, string alert_date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_Compliance_Calendar", ReplyAction="*")]
        System.Threading.Tasks.Task<int> Update_Compliance_CalendarAsync(int com_id, int dept_id, string Com_type, string Comp_Description, string duratn_type, string due_date, string alert_date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete_Compliance_Calendar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Delete_Compliance_Calendar(int com_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete_Compliance_Calendar", ReplyAction="*")]
        System.Threading.Tasks.Task<int> Delete_Compliance_CalendarAsync(int com_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_Compliance_type", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Select_Compliance_type(int dept_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_Compliance_type", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Select_Compliance_typeAsync(int dept_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_Compliance_REG", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Select_Compliance_REG(int dept_id, string com_type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_Compliance_REG", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Select_Compliance_REGAsync(int dept_id, string com_type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_Compliance_Dashboard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Select_Compliance_Dashboard(int dept_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_Compliance_Dashboard", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Select_Compliance_DashboardAsync(int dept_id);
        
        // CODEGEN: Parameter 'attachment1' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_Compliance_internal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Compliance_Register.ServiceReference1.Insert_Compliance_internalResponse Insert_Compliance_internal(Compliance_Register.ServiceReference1.Insert_Compliance_internalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_Compliance_internal", ReplyAction="*")]
        System.Threading.Tasks.Task<Compliance_Register.ServiceReference1.Insert_Compliance_internalResponse> Insert_Compliance_internalAsync(Compliance_Register.ServiceReference1.Insert_Compliance_internalRequest request);
        
        // CODEGEN: Parameter 'attachment1' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_Compliance_statutory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Compliance_Register.ServiceReference1.Insert_Compliance_statutoryResponse Insert_Compliance_statutory(Compliance_Register.ServiceReference1.Insert_Compliance_statutoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_Compliance_statutory", ReplyAction="*")]
        System.Threading.Tasks.Task<Compliance_Register.ServiceReference1.Insert_Compliance_statutoryResponse> Insert_Compliance_statutoryAsync(Compliance_Register.ServiceReference1.Insert_Compliance_statutoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/update_Compliance_status", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int update_Compliance_status(int com_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/update_Compliance_status", ReplyAction="*")]
        System.Threading.Tasks.Task<int> update_Compliance_statusAsync(int com_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_com_Register", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Select_com_Register(int dept_id, string com_type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_com_Register", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Select_com_RegisterAsync(int dept_id, string com_type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_file", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_file(int com_reg_id, string type_);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_file", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_fileAsync(int com_reg_id, string type_);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_for_HeadVerifn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Select_for_HeadVerifn(int dept_id, string com_type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_for_HeadVerifn", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Select_for_HeadVerifnAsync(int dept_id, string com_type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_for_CSVerifn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Select_for_CSVerifn(string com_type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_for_CSVerifn", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Select_for_CSVerifnAsync(string com_type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete_Compliance_Register", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Delete_Compliance_Register(int com_reg_id, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete_Compliance_Register", ReplyAction="*")]
        System.Threading.Tasks.Task<int> Delete_Compliance_RegisterAsync(int com_reg_id, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/update_Compliance_status_back", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int update_Compliance_status_back(int com_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/update_Compliance_status_back", ReplyAction="*")]
        System.Threading.Tasks.Task<int> update_Compliance_status_backAsync(int com_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_Verify_Head", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Update_Verify_Head(int com_reg_id, string verified_by, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_Verify_Head", ReplyAction="*")]
        System.Threading.Tasks.Task<int> Update_Verify_HeadAsync(int com_reg_id, string verified_by, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_Verify_CS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Update_Verify_CS(int com_reg_id, string verified_by, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_Verify_CS", ReplyAction="*")]
        System.Threading.Tasks.Task<int> Update_Verify_CSAsync(int com_reg_id, string verified_by, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_Head_dept", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Select_Head_dept(string emp_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_Head_dept", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Select_Head_deptAsync(string emp_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_for_Report", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Select_for_Report(string com_type, int dept_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_for_Report", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Select_for_ReportAsync(string com_type, int dept_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/update_Compliance_afterverify", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int update_Compliance_afterverify(int com_id, string due_date, string alert_on);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/update_Compliance_afterverify", ReplyAction="*")]
        System.Threading.Tasks.Task<int> update_Compliance_afterverifyAsync(int com_id, string due_date, string alert_on);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_AgreementRenewal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Insert_AgreementRenewal(int agrmnt_id, string agrmnt_type, string agrmnt_party, string date_of_exectn, string next_renewal, string first_alert, string second_alert, string third_alert, string updated_on, string updated_by);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_AgreementRenewal", ReplyAction="*")]
        System.Threading.Tasks.Task<int> Insert_AgreementRenewalAsync(int agrmnt_id, string agrmnt_type, string agrmnt_party, string date_of_exectn, string next_renewal, string first_alert, string second_alert, string third_alert, string updated_on, string updated_by);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/update_AgreementRenewal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int update_AgreementRenewal(int agrmnt_id, string agrmnt_type, string agrmnt_party, string date_of_exectn, string next_renewal, string first_alert, string second_alert, string third_alert, string updated_on, string updated_by);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/update_AgreementRenewal", ReplyAction="*")]
        System.Threading.Tasks.Task<int> update_AgreementRenewalAsync(int agrmnt_id, string agrmnt_type, string agrmnt_party, string date_of_exectn, string next_renewal, string first_alert, string second_alert, string third_alert, string updated_on, string updated_by);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_grid_Agrmnt_renewal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_grid_Agrmnt_renewal();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_grid_Agrmnt_renewal", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_grid_Agrmnt_renewalAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_Usage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Insert_Usage(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_Usage", ReplyAction="*")]
        System.Threading.Tasks.Task<int> Insert_UsageAsync(string username);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Insert_Compliance_internal", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Insert_Compliance_internalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int com_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string entered_by;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string entered_date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string verified_head;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string head_verify_date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string verified_cs;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string cs_verify_date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public int comp_status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string remarks;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] attachment1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        public string file_name1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=11)]
        public string contenttype1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=12)]
        public int status;
        
        public Insert_Compliance_internalRequest() {
        }
        
        public Insert_Compliance_internalRequest(int com_id, string entered_by, string entered_date, string verified_head, string head_verify_date, string verified_cs, string cs_verify_date, int comp_status, string remarks, byte[] attachment1, string file_name1, string contenttype1, int status) {
            this.com_id = com_id;
            this.entered_by = entered_by;
            this.entered_date = entered_date;
            this.verified_head = verified_head;
            this.head_verify_date = head_verify_date;
            this.verified_cs = verified_cs;
            this.cs_verify_date = cs_verify_date;
            this.comp_status = comp_status;
            this.remarks = remarks;
            this.attachment1 = attachment1;
            this.file_name1 = file_name1;
            this.contenttype1 = contenttype1;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Insert_Compliance_internalResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Insert_Compliance_internalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int Insert_Compliance_internalResult;
        
        public Insert_Compliance_internalResponse() {
        }
        
        public Insert_Compliance_internalResponse(int Insert_Compliance_internalResult) {
            this.Insert_Compliance_internalResult = Insert_Compliance_internalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Insert_Compliance_statutory", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Insert_Compliance_statutoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int com_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string entered_by;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string entered_date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string verified_head;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string head_verify_date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string verified_cs;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string cs_verify_date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public int comp_status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string remarks;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] attachment1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        public string file_name1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=11)]
        public string contenttype1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=12)]
        public int status;
        
        public Insert_Compliance_statutoryRequest() {
        }
        
        public Insert_Compliance_statutoryRequest(int com_id, string entered_by, string entered_date, string verified_head, string head_verify_date, string verified_cs, string cs_verify_date, int comp_status, string remarks, byte[] attachment1, string file_name1, string contenttype1, int status) {
            this.com_id = com_id;
            this.entered_by = entered_by;
            this.entered_date = entered_date;
            this.verified_head = verified_head;
            this.head_verify_date = head_verify_date;
            this.verified_cs = verified_cs;
            this.cs_verify_date = cs_verify_date;
            this.comp_status = comp_status;
            this.remarks = remarks;
            this.attachment1 = attachment1;
            this.file_name1 = file_name1;
            this.contenttype1 = contenttype1;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Insert_Compliance_statutoryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Insert_Compliance_statutoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int Insert_Compliance_statutoryResult;
        
        public Insert_Compliance_statutoryResponse() {
        }
        
        public Insert_Compliance_statutoryResponse(int Insert_Compliance_statutoryResult) {
            this.Insert_Compliance_statutoryResult = Insert_Compliance_statutoryResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService_Compliance_RegisterSoapChannel : Compliance_Register.ServiceReference1.WebService_Compliance_RegisterSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService_Compliance_RegisterSoapClient : System.ServiceModel.ClientBase<Compliance_Register.ServiceReference1.WebService_Compliance_RegisterSoap>, Compliance_Register.ServiceReference1.WebService_Compliance_RegisterSoap {
        
        public WebService_Compliance_RegisterSoapClient() {
        }
        
        public WebService_Compliance_RegisterSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService_Compliance_RegisterSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_Compliance_RegisterSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_Compliance_RegisterSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet Get_login(string username, string password) {
            return base.Channel.Get_login(username, password);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_loginAsync(string username, string password) {
            return base.Channel.Get_loginAsync(username, password);
        }
        
        public System.Data.DataSet Get_depertment() {
            return base.Channel.Get_depertment();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_depertmentAsync() {
            return base.Channel.Get_depertmentAsync();
        }
        
        public System.Data.DataSet Get_grid() {
            return base.Channel.Get_grid();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_gridAsync() {
            return base.Channel.Get_gridAsync();
        }
        
        public System.Data.DataSet Get_gridbyid(int dept_id) {
            return base.Channel.Get_gridbyid(dept_id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_gridbyidAsync(int dept_id) {
            return base.Channel.Get_gridbyidAsync(dept_id);
        }
        
        public string[] GetEmpNames(string empcode) {
            return base.Channel.GetEmpNames(empcode);
        }
        
        public System.Threading.Tasks.Task<string[]> GetEmpNamesAsync(string empcode) {
            return base.Channel.GetEmpNamesAsync(empcode);
        }
        
        public System.Data.DataSet Get_empcode(string empcode) {
            return base.Channel.Get_empcode(empcode);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_empcodeAsync(string empcode) {
            return base.Channel.Get_empcodeAsync(empcode);
        }
        
        public int Insert_Compliance_Reg(int dept_id, string dept_head, int status) {
            return base.Channel.Insert_Compliance_Reg(dept_id, dept_head, status);
        }
        
        public System.Threading.Tasks.Task<int> Insert_Compliance_RegAsync(int dept_id, string dept_head, int status) {
            return base.Channel.Insert_Compliance_RegAsync(dept_id, dept_head, status);
        }
        
        public int Insert_Compliance_Calendar(int dept_id, string Com_type, string Comp_Description, string duratn_type, string due_date, string alert_date) {
            return base.Channel.Insert_Compliance_Calendar(dept_id, Com_type, Comp_Description, duratn_type, due_date, alert_date);
        }
        
        public System.Threading.Tasks.Task<int> Insert_Compliance_CalendarAsync(int dept_id, string Com_type, string Comp_Description, string duratn_type, string due_date, string alert_date) {
            return base.Channel.Insert_Compliance_CalendarAsync(dept_id, Com_type, Comp_Description, duratn_type, due_date, alert_date);
        }
        
        public System.Data.DataSet Get_grid_Calendar(int dept_id) {
            return base.Channel.Get_grid_Calendar(dept_id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_grid_CalendarAsync(int dept_id) {
            return base.Channel.Get_grid_CalendarAsync(dept_id);
        }
        
        public int Update_Compliance_Calendar(int com_id, int dept_id, string Com_type, string Comp_Description, string duratn_type, string due_date, string alert_date) {
            return base.Channel.Update_Compliance_Calendar(com_id, dept_id, Com_type, Comp_Description, duratn_type, due_date, alert_date);
        }
        
        public System.Threading.Tasks.Task<int> Update_Compliance_CalendarAsync(int com_id, int dept_id, string Com_type, string Comp_Description, string duratn_type, string due_date, string alert_date) {
            return base.Channel.Update_Compliance_CalendarAsync(com_id, dept_id, Com_type, Comp_Description, duratn_type, due_date, alert_date);
        }
        
        public int Delete_Compliance_Calendar(int com_id) {
            return base.Channel.Delete_Compliance_Calendar(com_id);
        }
        
        public System.Threading.Tasks.Task<int> Delete_Compliance_CalendarAsync(int com_id) {
            return base.Channel.Delete_Compliance_CalendarAsync(com_id);
        }
        
        public System.Data.DataSet Select_Compliance_type(int dept_id) {
            return base.Channel.Select_Compliance_type(dept_id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Select_Compliance_typeAsync(int dept_id) {
            return base.Channel.Select_Compliance_typeAsync(dept_id);
        }
        
        public System.Data.DataSet Select_Compliance_REG(int dept_id, string com_type) {
            return base.Channel.Select_Compliance_REG(dept_id, com_type);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Select_Compliance_REGAsync(int dept_id, string com_type) {
            return base.Channel.Select_Compliance_REGAsync(dept_id, com_type);
        }
        
        public System.Data.DataSet Select_Compliance_Dashboard(int dept_id) {
            return base.Channel.Select_Compliance_Dashboard(dept_id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Select_Compliance_DashboardAsync(int dept_id) {
            return base.Channel.Select_Compliance_DashboardAsync(dept_id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Compliance_Register.ServiceReference1.Insert_Compliance_internalResponse Compliance_Register.ServiceReference1.WebService_Compliance_RegisterSoap.Insert_Compliance_internal(Compliance_Register.ServiceReference1.Insert_Compliance_internalRequest request) {
            return base.Channel.Insert_Compliance_internal(request);
        }
        
        public int Insert_Compliance_internal(int com_id, string entered_by, string entered_date, string verified_head, string head_verify_date, string verified_cs, string cs_verify_date, int comp_status, string remarks, byte[] attachment1, string file_name1, string contenttype1, int status) {
            Compliance_Register.ServiceReference1.Insert_Compliance_internalRequest inValue = new Compliance_Register.ServiceReference1.Insert_Compliance_internalRequest();
            inValue.com_id = com_id;
            inValue.entered_by = entered_by;
            inValue.entered_date = entered_date;
            inValue.verified_head = verified_head;
            inValue.head_verify_date = head_verify_date;
            inValue.verified_cs = verified_cs;
            inValue.cs_verify_date = cs_verify_date;
            inValue.comp_status = comp_status;
            inValue.remarks = remarks;
            inValue.attachment1 = attachment1;
            inValue.file_name1 = file_name1;
            inValue.contenttype1 = contenttype1;
            inValue.status = status;
            Compliance_Register.ServiceReference1.Insert_Compliance_internalResponse retVal = ((Compliance_Register.ServiceReference1.WebService_Compliance_RegisterSoap)(this)).Insert_Compliance_internal(inValue);
            return retVal.Insert_Compliance_internalResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Compliance_Register.ServiceReference1.Insert_Compliance_internalResponse> Compliance_Register.ServiceReference1.WebService_Compliance_RegisterSoap.Insert_Compliance_internalAsync(Compliance_Register.ServiceReference1.Insert_Compliance_internalRequest request) {
            return base.Channel.Insert_Compliance_internalAsync(request);
        }
        
        public System.Threading.Tasks.Task<Compliance_Register.ServiceReference1.Insert_Compliance_internalResponse> Insert_Compliance_internalAsync(int com_id, string entered_by, string entered_date, string verified_head, string head_verify_date, string verified_cs, string cs_verify_date, int comp_status, string remarks, byte[] attachment1, string file_name1, string contenttype1, int status) {
            Compliance_Register.ServiceReference1.Insert_Compliance_internalRequest inValue = new Compliance_Register.ServiceReference1.Insert_Compliance_internalRequest();
            inValue.com_id = com_id;
            inValue.entered_by = entered_by;
            inValue.entered_date = entered_date;
            inValue.verified_head = verified_head;
            inValue.head_verify_date = head_verify_date;
            inValue.verified_cs = verified_cs;
            inValue.cs_verify_date = cs_verify_date;
            inValue.comp_status = comp_status;
            inValue.remarks = remarks;
            inValue.attachment1 = attachment1;
            inValue.file_name1 = file_name1;
            inValue.contenttype1 = contenttype1;
            inValue.status = status;
            return ((Compliance_Register.ServiceReference1.WebService_Compliance_RegisterSoap)(this)).Insert_Compliance_internalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Compliance_Register.ServiceReference1.Insert_Compliance_statutoryResponse Compliance_Register.ServiceReference1.WebService_Compliance_RegisterSoap.Insert_Compliance_statutory(Compliance_Register.ServiceReference1.Insert_Compliance_statutoryRequest request) {
            return base.Channel.Insert_Compliance_statutory(request);
        }
        
        public int Insert_Compliance_statutory(int com_id, string entered_by, string entered_date, string verified_head, string head_verify_date, string verified_cs, string cs_verify_date, int comp_status, string remarks, byte[] attachment1, string file_name1, string contenttype1, int status) {
            Compliance_Register.ServiceReference1.Insert_Compliance_statutoryRequest inValue = new Compliance_Register.ServiceReference1.Insert_Compliance_statutoryRequest();
            inValue.com_id = com_id;
            inValue.entered_by = entered_by;
            inValue.entered_date = entered_date;
            inValue.verified_head = verified_head;
            inValue.head_verify_date = head_verify_date;
            inValue.verified_cs = verified_cs;
            inValue.cs_verify_date = cs_verify_date;
            inValue.comp_status = comp_status;
            inValue.remarks = remarks;
            inValue.attachment1 = attachment1;
            inValue.file_name1 = file_name1;
            inValue.contenttype1 = contenttype1;
            inValue.status = status;
            Compliance_Register.ServiceReference1.Insert_Compliance_statutoryResponse retVal = ((Compliance_Register.ServiceReference1.WebService_Compliance_RegisterSoap)(this)).Insert_Compliance_statutory(inValue);
            return retVal.Insert_Compliance_statutoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Compliance_Register.ServiceReference1.Insert_Compliance_statutoryResponse> Compliance_Register.ServiceReference1.WebService_Compliance_RegisterSoap.Insert_Compliance_statutoryAsync(Compliance_Register.ServiceReference1.Insert_Compliance_statutoryRequest request) {
            return base.Channel.Insert_Compliance_statutoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<Compliance_Register.ServiceReference1.Insert_Compliance_statutoryResponse> Insert_Compliance_statutoryAsync(int com_id, string entered_by, string entered_date, string verified_head, string head_verify_date, string verified_cs, string cs_verify_date, int comp_status, string remarks, byte[] attachment1, string file_name1, string contenttype1, int status) {
            Compliance_Register.ServiceReference1.Insert_Compliance_statutoryRequest inValue = new Compliance_Register.ServiceReference1.Insert_Compliance_statutoryRequest();
            inValue.com_id = com_id;
            inValue.entered_by = entered_by;
            inValue.entered_date = entered_date;
            inValue.verified_head = verified_head;
            inValue.head_verify_date = head_verify_date;
            inValue.verified_cs = verified_cs;
            inValue.cs_verify_date = cs_verify_date;
            inValue.comp_status = comp_status;
            inValue.remarks = remarks;
            inValue.attachment1 = attachment1;
            inValue.file_name1 = file_name1;
            inValue.contenttype1 = contenttype1;
            inValue.status = status;
            return ((Compliance_Register.ServiceReference1.WebService_Compliance_RegisterSoap)(this)).Insert_Compliance_statutoryAsync(inValue);
        }
        
        public int update_Compliance_status(int com_id) {
            return base.Channel.update_Compliance_status(com_id);
        }
        
        public System.Threading.Tasks.Task<int> update_Compliance_statusAsync(int com_id) {
            return base.Channel.update_Compliance_statusAsync(com_id);
        }
        
        public System.Data.DataSet Select_com_Register(int dept_id, string com_type) {
            return base.Channel.Select_com_Register(dept_id, com_type);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Select_com_RegisterAsync(int dept_id, string com_type) {
            return base.Channel.Select_com_RegisterAsync(dept_id, com_type);
        }
        
        public System.Data.DataSet Get_file(int com_reg_id, string type_) {
            return base.Channel.Get_file(com_reg_id, type_);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_fileAsync(int com_reg_id, string type_) {
            return base.Channel.Get_fileAsync(com_reg_id, type_);
        }
        
        public System.Data.DataSet Select_for_HeadVerifn(int dept_id, string com_type) {
            return base.Channel.Select_for_HeadVerifn(dept_id, com_type);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Select_for_HeadVerifnAsync(int dept_id, string com_type) {
            return base.Channel.Select_for_HeadVerifnAsync(dept_id, com_type);
        }
        
        public System.Data.DataSet Select_for_CSVerifn(string com_type) {
            return base.Channel.Select_for_CSVerifn(com_type);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Select_for_CSVerifnAsync(string com_type) {
            return base.Channel.Select_for_CSVerifnAsync(com_type);
        }
        
        public int Delete_Compliance_Register(int com_reg_id, string status) {
            return base.Channel.Delete_Compliance_Register(com_reg_id, status);
        }
        
        public System.Threading.Tasks.Task<int> Delete_Compliance_RegisterAsync(int com_reg_id, string status) {
            return base.Channel.Delete_Compliance_RegisterAsync(com_reg_id, status);
        }
        
        public int update_Compliance_status_back(int com_id) {
            return base.Channel.update_Compliance_status_back(com_id);
        }
        
        public System.Threading.Tasks.Task<int> update_Compliance_status_backAsync(int com_id) {
            return base.Channel.update_Compliance_status_backAsync(com_id);
        }
        
        public int Update_Verify_Head(int com_reg_id, string verified_by, string type) {
            return base.Channel.Update_Verify_Head(com_reg_id, verified_by, type);
        }
        
        public System.Threading.Tasks.Task<int> Update_Verify_HeadAsync(int com_reg_id, string verified_by, string type) {
            return base.Channel.Update_Verify_HeadAsync(com_reg_id, verified_by, type);
        }
        
        public int Update_Verify_CS(int com_reg_id, string verified_by, string type) {
            return base.Channel.Update_Verify_CS(com_reg_id, verified_by, type);
        }
        
        public System.Threading.Tasks.Task<int> Update_Verify_CSAsync(int com_reg_id, string verified_by, string type) {
            return base.Channel.Update_Verify_CSAsync(com_reg_id, verified_by, type);
        }
        
        public System.Data.DataSet Select_Head_dept(string emp_code) {
            return base.Channel.Select_Head_dept(emp_code);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Select_Head_deptAsync(string emp_code) {
            return base.Channel.Select_Head_deptAsync(emp_code);
        }
        
        public System.Data.DataSet Select_for_Report(string com_type, int dept_id) {
            return base.Channel.Select_for_Report(com_type, dept_id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Select_for_ReportAsync(string com_type, int dept_id) {
            return base.Channel.Select_for_ReportAsync(com_type, dept_id);
        }
        
        public int update_Compliance_afterverify(int com_id, string due_date, string alert_on) {
            return base.Channel.update_Compliance_afterverify(com_id, due_date, alert_on);
        }
        
        public System.Threading.Tasks.Task<int> update_Compliance_afterverifyAsync(int com_id, string due_date, string alert_on) {
            return base.Channel.update_Compliance_afterverifyAsync(com_id, due_date, alert_on);
        }
        
        public int Insert_AgreementRenewal(int agrmnt_id, string agrmnt_type, string agrmnt_party, string date_of_exectn, string next_renewal, string first_alert, string second_alert, string third_alert, string updated_on, string updated_by) {
            return base.Channel.Insert_AgreementRenewal(agrmnt_id, agrmnt_type, agrmnt_party, date_of_exectn, next_renewal, first_alert, second_alert, third_alert, updated_on, updated_by);
        }
        
        public System.Threading.Tasks.Task<int> Insert_AgreementRenewalAsync(int agrmnt_id, string agrmnt_type, string agrmnt_party, string date_of_exectn, string next_renewal, string first_alert, string second_alert, string third_alert, string updated_on, string updated_by) {
            return base.Channel.Insert_AgreementRenewalAsync(agrmnt_id, agrmnt_type, agrmnt_party, date_of_exectn, next_renewal, first_alert, second_alert, third_alert, updated_on, updated_by);
        }
        
        public int update_AgreementRenewal(int agrmnt_id, string agrmnt_type, string agrmnt_party, string date_of_exectn, string next_renewal, string first_alert, string second_alert, string third_alert, string updated_on, string updated_by) {
            return base.Channel.update_AgreementRenewal(agrmnt_id, agrmnt_type, agrmnt_party, date_of_exectn, next_renewal, first_alert, second_alert, third_alert, updated_on, updated_by);
        }
        
        public System.Threading.Tasks.Task<int> update_AgreementRenewalAsync(int agrmnt_id, string agrmnt_type, string agrmnt_party, string date_of_exectn, string next_renewal, string first_alert, string second_alert, string third_alert, string updated_on, string updated_by) {
            return base.Channel.update_AgreementRenewalAsync(agrmnt_id, agrmnt_type, agrmnt_party, date_of_exectn, next_renewal, first_alert, second_alert, third_alert, updated_on, updated_by);
        }
        
        public System.Data.DataSet Get_grid_Agrmnt_renewal() {
            return base.Channel.Get_grid_Agrmnt_renewal();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_grid_Agrmnt_renewalAsync() {
            return base.Channel.Get_grid_Agrmnt_renewalAsync();
        }
        
        public int Insert_Usage(string username) {
            return base.Channel.Insert_Usage(username);
        }
        
        public System.Threading.Tasks.Task<int> Insert_UsageAsync(string username) {
            return base.Channel.Insert_UsageAsync(username);
        }
    }
}
